Repository rapidsai/rapids-cmake, pull requests merged in 2021-08, with the labels that each got.

#48 Tests now can be SERIAL and use FetchContent to get rapids-cmake
  testing/utils/cmake_build_test.cmake
  testing/utils/cmake_config_test.cmake
  testing/utils/cmake_test.cmake
  testing/utils/project_template.cmake.in
Labels: 3 - Ready for Review, feature request, non-breaking, tests

#55 rapids_export(BUILD) only creates alias targets to existing targets
  rapids-cmake/export/template/config.cmake.in
Labels: bug, non-breaking, 3 - Ready for Review

#57 rapids_export will always install cmake files to `lib`
  rapids-cmake/export/export.cmake
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review, conda

#54 rapids_find_package propagates variables from find_package
  rapids-cmake/find/package.cmake
  testing/find/CMakeLists.txt
  testing/find/find_package-no-variable-leak.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#62 cmake-format: Now aware of `rapids_cmake_support_conda_env` flags
  cmake-format-rapids-cmake.json
Labels: doc, non-breaking, 3 - Ready for Review

#63 Ensure that all rapids-cmake files have include guards
  rapids-cmake/export/cpm.cmake
  rapids-cmake/export/find_package_file.cmake
  rapids-cmake/export/package.cmake
  rapids-cmake/export/write_dependencies.cmake
  rapids-cmake/export/write_language.cmake
Labels: improvement, non-breaking, 3 - Ready for Review

#64 Introduce rapids_export_find_package_root command
  cmake-format-rapids-cmake.json
  docs/command/rapids_export_find_package_root.rst
  rapids-cmake/export/find_package_root.cmake
  rapids-cmake/export/write_dependencies.cmake
  testing/export/CMakeLists.txt
  testing/export/write_dependencies-root-dirs.cmake
Labels: feature request, non-breaking

#65 rapids_export_cpm(BUILD) captures location of locally found packages
  rapids-cmake/export/cpm.cmake
  rapids-cmake/export/template/cpm.cmake.in
  testing/export/CMakeLists.txt
  testing/export/export_cpm-build-possible-dir.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#52 Introduce rapids_cpm_<preset>
  CONTRIBUTING.md
  cmake-format-rapids-cmake.json
  docs/api.rst
  docs/packages/example.json
  docs/packages/rapids_cpm_gtest.rst
  docs/packages/rapids_cpm_nvbench.rst
  docs/packages/rapids_cpm_rmm.rst
  docs/packages/rapids_cpm_spdlog.rst
  docs/packages/rapids_cpm_thrust.rst
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/download.cmake
  rapids-cmake/cpm/detail/load_preset_versions.cmake
  rapids-cmake/cpm/detail/package_details.cmake
  rapids-cmake/cpm/find.cmake
  rapids-cmake/cpm/gtest.cmake
  rapids-cmake/cpm/init.cmake
  rapids-cmake/cpm/nvbench.cmake
  rapids-cmake/cpm/rmm.cmake
  rapids-cmake/cpm/spdlog.cmake
  rapids-cmake/cpm/thrust.cmake
  rapids-cmake/cpm/versions.json
  rapids-cmake/export/write_dependencies.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_gtest-export.cmake
  testing/cpm/cpm_gtest-simple.cmake
  testing/cpm/cpm_nvbench-export.cmake
  testing/cpm/cpm_nvbench-simple.cmake
  testing/cpm/cpm_rmm-export.cmake
  testing/cpm/cpm_rmm-simple.cmake
  testing/cpm/cpm_spdlog-export.cmake
  testing/cpm/cpm_spdlog-simple.cmake
  testing/cpm/cpm_thrust-export.cmake
  testing/cpm/cpm_thrust-simple.cmake
  testing/cpm/setup_cpm_cache.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#68 rapids_export_package(BUILD) captures location of locally found packages
  rapids-cmake/export/cpm.cmake
  rapids-cmake/export/package.cmake
  rapids-cmake/export/template/build_package.cmake.in
  rapids-cmake/export/template/install_package.cmake.in
  rapids-cmake/export/write_dependencies.cmake
  testing/export/CMakeLists.txt
  testing/export/export_cpm-build-possible-dir.cmake
  testing/export/export_cpm-build.cmake
  testing/export/export_cpm-install.cmake
  testing/export/export_cpm-options-escaped.cmake
  testing/export/export_package-build-possible-dir.cmake
  testing/export/export_package-build.cmake
  testing/export/export_package-install-possible-dir.cmake
  testing/export/export_package-install.cmake
  testing/export/write_dependencies-duplicate-cpm-and-package.cmake
  testing/export/write_dependencies-duplicate-cpm.cmake
  testing/export/write_dependencies-multiple-directories/CMakeLists.txt
Labels: feature request, non-breaking, 3 - Ready for Review

#69 [REVIEW] FIX Install sphinxcontrib-moderncmakedomain in docs script
  ci/docs/build.sh
Labels: bug, non-breaking

#70 rapids_cpm_thrust specifies the correct install variable
  rapids-cmake/cpm/thrust.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#71 Make sure rapids_cpm_spdlog specifies the correct spdlog global targets
  rapids-cmake/cpm/spdlog.cmake
Labels: bug, non-breaking, 3 - Ready for Review
