Repository rapidsai/rapids-cmake, pull requests merged in 2021-09, with the labels that each got.

#75 rapids_export verify DOCUMENTATION and FINAL_CODE_BLOCK exist
  rapids-cmake/export/export.cmake
  testing/export/CMakeLists.txt
  testing/export/export-verify-bad-code-block-var.cmake
  testing/export/export-verify-bad-doc-var.cmake
  testing/utils/cmake_test.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#76 Add rapids_export_find_package_root to api doc page
  docs/api.rst
Labels: doc, non-breaking, 3 - Ready for Review

#74 Allow projects to override version.json information
  cmake-format-rapids-cmake.json
  docs/api.rst
  docs/command/rapids_cpm_package_override.rst
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/package_details.cmake
  rapids-cmake/cpm/init.cmake
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_init-bad-override-path.cmake
  testing/cpm/cpm_init-override-multiple.cmake
  testing/cpm/cpm_init-override-simple.cmake
  testing/cpm/cpm_package_override-bad-path.cmake
  testing/cpm/cpm_package_override-before-init.cmake
  testing/cpm/cpm_package_override-multiple.cmake
  testing/cpm/cpm_package_override-simple.cmake
  testing/utils/cmake_test.cmake
Labels: feature request, non-breaking, 5 - Ready to Merge

#79 rapids-cmake SHOULD_FAIL tests verify the CMake Error string
  testing/cpm/CMakeLists.txt
  testing/export/CMakeLists.txt
  testing/utils/cmake_test.cmake
Labels: feature request, non-breaking, 3 - Ready for Review, tests

#80 Make sure rapids-cmake doesn't produce CMake syntax warnings
  rapids-cmake/cpm/package_override.cmake
  testing/utils/cmake_test.cmake
Labels: bug, non-breaking, 3 - Ready for Review, Code quality

#82 Remove unneeded inclusions of the old setup_cpm_cache.cmake
  testing/cpm/cpm_init-bad-override-path.cmake
  testing/cpm/cpm_init-override-multiple.cmake
  testing/cpm/cpm_init-override-simple.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#84 Update update-version.sh [skip-ci]
  ci/release/update-version.sh
Labels: doc, non-breaking, 3 - Ready for Review
