Repository rapidsai/rapids-cmake, pull requests merged in 2021-12, with the labels that each got.

#135 Set the `always_download` value in versions.json to the common case
  docs/packages/example.json
Labels: doc, non-breaking, 3 - Ready for Review

#136 Remove rapids_cmake_install_lib_dir unstable side effect checks
  testing/cmake/install_lib_dir-build.cmake
  testing/cmake/install_lib_dir-prefix.cmake
Labels: improvement, non-breaking, 3 - Ready for Review, tests

#140 Fix type-o in docs `<PackageName>_BINARY_DIR` instead of `<PackageName>_BINAR_DIR`
  rapids-cmake/cpm/find.cmake
Labels: doc, non-breaking

#142 Fix typos
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  rapids-cmake/cmake/parse_version.cmake
  rapids-cmake/cmake/support_conda_env.cmake
Labels: doc, non-breaking
