Repository rapidsai/rapids-cmake, pull requests merged in 2021-07, with the labels that each got.

#39 Correct regression specify rapids-cmake-dir as a cache variable
  CMakeLists.txt
Labels: ! - Hotfix, bug

#40 Make sure that rapids-cmake-dir cache variable is hidden
  CMakeLists.txt
Labels: bug

#42 add ci cmake formatting hooks
  CMakeLists.txt
  ci/checks/cmake_config_format.json
  ci/checks/cmake_config_lint.json
  ci/checks/cmake_config_testing_lint.json
  ci/checks/style.sh
  ci/release/update-version.sh
  rapids-cmake/cmake/build_type.cmake
  rapids-cmake/cmake/make_global.cmake
  rapids-cmake/cmake/parse_version.cmake
  rapids-cmake/cmake/support_conda_env.cmake
  rapids-cmake/cmake/write_version_file.cmake
  rapids-cmake/cpm/find.cmake
  rapids-cmake/cpm/init.cmake
  rapids-cmake/cuda/detail/detect_architectures.cmake
  rapids-cmake/cuda/detail/invoke_set_all_architectures.cmake
  rapids-cmake/cuda/detail/invoke_set_native_architectures.cmake
  rapids-cmake/cuda/init_architectures.cmake
  rapids-cmake/cuda/init_runtime.cmake
  rapids-cmake/cuda/set_architectures.cmake
  rapids-cmake/export/cpm.cmake
  rapids-cmake/export/export.cmake
  rapids-cmake/export/find_package_file.cmake
  rapids-cmake/export/package.cmake
  rapids-cmake/export/write_dependencies.cmake
  rapids-cmake/export/write_language.cmake
  rapids-cmake/find/generate_module.cmake
  rapids-cmake/find/package.cmake
Labels: feature request, non-breaking

#43 ci/gpu/build.sh uses git tags to properly compute conda env
  ci/gpu/build.sh
Labels: 3 - Ready for Review, bug, containers, non-breaking

#46 rapids-cmake tests properly state what C++ std levels they require
  testing/cmake/write_version-absolute/CMakeLists.txt
  testing/cmake/write_version-leading-zeroes/CMakeLists.txt
  testing/cmake/write_version-relative/CMakeLists.txt
Labels: 3 - Ready for Review, bug, non-breaking

#37 rapids_export version support expanded to handle more use-cases
  cmake-format-rapids-cmake.json
  rapids-cmake/export/detail/parse_version.cmake
  rapids-cmake/export/export.cmake
  rapids-cmake/export/template/config.cmake.in
  testing/export/CMakeLists.txt
  testing/export/export-verify-explicit-disabled-version.cmake
  testing/export/export-verify-explicit-major-version-only-matching.cmake
  testing/export/export-verify-explicit-version-value.cmake
  testing/export/export-verify-implicit-disabled-version.cmake
  testing/export/export-verify-implicit-major-version-only-matching.cmake
Labels: 3 - Ready for Review, feature request, non-breaking

#47 Bug/correct invalid generate module doc layout
  rapids-cmake/find/generate_module.cmake
Labels: 3 - Ready for Review, doc, non-breaking

#44 ENH Replace gpuci_conda_retry with gpuci_mamba_retry
  ci/gpu/build.sh
Labels: improvement, non-breaking
