Repository rapidsai/rapids-cmake, pull requests merged in 2021-11, with the labels that each got.

#110 Build directory config.cmake now sets the correct targets to global
  rapids-cmake/export/template/config.cmake.in
  testing/export/CMakeLists.txt
  testing/export/export-verify-global-targets/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#119 [FIX] Require the exact version of Thrust in the versions.json file
  rapids-cmake/cpm/thrust.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#120 rapids_cpm_thrust doesn't place temp file in a searched location
  rapids-cmake/cpm/thrust.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#122 rapids_cpm_libcudacxx ensures CMAKE_INSTALL_INCLUDEDIR exists
  rapids-cmake/cmake/install_lib_dir.cmake
  rapids-cmake/cpm/libcudacxx.cmake
  testing/cmake/CMakeLists.txt
  testing/cmake/install_lib_dir-after-gnuinstalldir-include.cmake
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#121 rapids_cpm_find restores CPM variables when project was already added
  rapids-cmake/cpm/find.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_find-restore-cpm-vars/CMakeLists.txt
  testing/cpm/cpm_find-restore-cpm-vars/mock_zlib_source_dir/CMakeLists.txt
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#124 rapids_cpm_libcudacxx install logic is safe for multiple inclusion
  rapids-cmake/cpm/libcudacxx.cmake
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#131 Document how to control the git rep/tag that RAPIDS.cmake uses
  README.md
  docs/basics.rst
Labels: doc, non-breaking, 3 - Ready for Review

#132 Correct minor formatting issues
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cuda/init_runtime.cmake
  testing/cpm/cpm_nvbench-export.cmake
Labels: doc, non-breaking, 5 - Ready to Merge
