Repository rapidsai/rapids-cmake, pull requests merged in 2022-10, with the labels that each got.

#265 Switch thrust over to use rapids-cmake patches
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/cpm/patches/Thrust/install_rules.diff
  rapids-cmake/cpm/thrust.cmake
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#284 Enable copy_prs ops-bot config
  .github/ops-bot.yaml
Labels: feature request, non-breaking, 3 - Ready for Review

#279 Clarify rapids_cuda_init_architectures behavior
  rapids-cmake/cuda/init_architectures.cmake
Labels: doc, non-breaking, 3 - Ready for Review

#285 Add sm90 ( Hopper ) to rapids-cmake "ALL" mode
  rapids-cmake/cuda/set_architectures.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#286 Update to nvcomp 2.4.1 to fix zstd decompression
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#280 Update pull request template to match rest of RAPIDS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: doc, non-breaking, 3 - Ready for Review

#289 Add `current_json_dir` placeholder in json patch file values
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/generate_patch_command.cmake
  rapids-cmake/cpm/detail/load_preset_versions.cmake
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_generate_patch_command-current_json_dir.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#292 Patch results are only displayed once per invocation of CMake
  rapids-cmake/cpm/detail/display_patch_status.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#293 Add support for cloning Google benchmark
  cmake-format-rapids-cmake.json
  docs/api.rst
  docs/packages/rapids_cpm_gbench.rst
  rapids-cmake/cpm/gbench.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_gbench-export.cmake
  testing/cpm/cpm_gbench-simple.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: feature request, non-breaking, 3 - Ready for Review

#294 Add missing CPM_ARGS to gbench
  rapids-cmake/cpm/gbench.cmake
Labels: bug, non-breaking, 3 - Ready for Review
