Repository rapidsai/rapids-cmake, pull requests merged in 2022-05, with the labels that each got.

#184 Add rapids-cython component for scikit-build based Python package builds
  .gitignore
  cmake-format-rapids-cmake.json
  rapids-cmake/cython/create_modules.cmake
  rapids-cmake/cython/detail/skbuild_patches.cmake
  rapids-cmake/cython/detail/verify_init.cmake
  rapids-cmake/cython/init.cmake
  rapids-cmake/rapids-cython.cmake
  testing/CMakeLists.txt
  testing/cython/CMakeLists.txt
  testing/cython/create_modules/CMakeLists.txt
  testing/cython/create_modules/test.pyx
  testing/cython/create_modules_errors.cmake
  testing/cython/create_modules_with_library/CMakeLists.txt
  testing/cython/create_modules_with_library/test.pyx
  testing/cython/init.cmake
  testing/cython/rapids-cython.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: feature request, non-breaking

#187 Use target name variable.
  rapids-cmake/cmake/write_git_revision_file.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#189 Default Cython module RUNPATH to $ORIGIN and return the list of created targets
  rapids-cmake/cython/create_modules.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#194 nvcomp install rules need to match the pre-built layout
  rapids-cmake/cpm/nvcomp.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#193 Update nvbench tag
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review

#197 Add rapids_cython to the html docs
  README.md
  docs/api.rst
  docs/command/rapids_cython_create_modules.rst
  docs/command/rapids_cython_init.rst
  rapids-cmake/cython/init.cmake
Labels: doc, non-breaking, 5 - Ready to Merge
