Repository rapidsai/rapids-cmake, pull requests merged in 2022-01, with the labels that each got.

#130 rapids_cpm_libcudacxx handle CPM already finding libcudacxx before being called
  rapids-cmake/cpm/libcudacxx.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_libcudacxx-after_cpmfind.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#134 Update Changelog to capture all 21.08 and 21.10 changes
  CHANGELOG.md
Labels: doc, non-breaking, 3 - Ready for Review

#144 Update NVBench for 22.02 to be the latest version
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#138 Update rapids-cmake packages to Thrust 1.15
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#145 rapids-cmake now supports an empty package entry in the override file
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_package_override-empty.cmake
  testing/cpm/cpm_package_override-simple.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#146 Ensure that nvbench doesn't require nvml when `CUDA::nvml` doesn't exist
  rapids-cmake/cpm/nvbench.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#137 add exclude_from_all flag to version.json
  cmake-format-rapids-cmake.json
  docs/packages/example.json
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/package_details.cmake
  rapids-cmake/cpm/gtest.cmake
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/nvbench.cmake
  rapids-cmake/cpm/rmm.cmake
  rapids-cmake/cpm/spdlog.cmake
  rapids-cmake/cpm/thrust.cmake
  testing/cpm/cpm_init-override-multiple.cmake
  testing/cpm/cpm_init-override-simple.cmake
  testing/cpm/cpm_libcudacxx-after_cpmfind.cmake
  testing/cpm/cpm_package_override-before-init.cmake
  testing/cpm/cpm_package_override-multiple.cmake
  testing/cpm/cpm_package_override-simple.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#143 Update rapids-cmake packages to libcudacxx 1.7
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 2 - In Progress

#147 Add CMake intersphinx support
  docs/conf.py
  docs/dependency_tracking.rst
  rapids-cmake/cmake/install_lib_dir.cmake
  rapids-cmake/cmake/make_global.cmake
  rapids-cmake/cmake/support_conda_env.cmake
  rapids-cmake/cmake/write_git_revision_file.cmake
  rapids-cmake/cmake/write_version_file.cmake
Labels: doc, non-breaking

#153 Example explains when you should use `rapids_find_generate_module`
  example/CMakeLists.txt
Labels: doc, non-breaking, 3 - Ready for Review

#149 rapids_export generated config.cmake no longer leaks variables
  rapids-cmake/export/template/config.cmake.in
Labels: bug, non-breaking, 3 - Ready for Review

#155 cpm_thrust would fail when provided only an install export set
  rapids-cmake/cpm/thrust.cmake
  testing/cpm/cpm_thrust-export.cmake
Labels: bug, non-breaking, 3 - Ready for Review
