Repository rapidsai/rapids-cmake, pull requests merged in 2022-09, with the labels that each got.

#261 Update cuCollections to fix issue with INSTALL_CUCO set to OFF.
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#262 Branch 22.10 merge 22.08
  CHANGELOG.md
Labels: feature request, non-breaking, 5 - Ready to Merge

#255 Handle reconfiguring with USE_PROPRIETARY_BINARY value differing
  rapids-cmake/cpm/nvcomp.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#260 Introduce rapids_cuda_patch_toolkit
  README.md
  docs/api.rst
  docs/command/rapids_cuda_patch_toolkit.rst
  rapids-cmake/cuda/patch_toolkit.cmake
  rapids-cmake/find/package.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/patch_toolkit-nested/CMakeLists.txt
  testing/cuda/patch_toolkit-nested/subdir/CMakeLists.txt
  testing/cuda/patch_toolkit.cmake
  testing/find/CMakeLists.txt
  testing/find/find_package-cudatoolkit-patching.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#263 conda_env: pass conda prefix as a rpath-link directory
  rapids-cmake/cmake/support_conda_env.cmake
  testing/cmake/conda_env-build.cmake
  testing/cmake/conda_env-prefix.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#266 [FIX] Ensure `<pkg>_FOUND` is set in the generated `Find<pkg>.cmake` file
  rapids-cmake/find/template/find_module.cmake.in
  testing/find/find_generate_module-build/CMakeLists.txt
  testing/find/find_generate_module-header-only/CMakeLists.txt
  testing/find/find_generate_module-install/CMakeLists.txt
Labels: improvement, non-breaking, 3 - Ready for Review

#257 [FEA] Use the GitHub `.zip` URI instead of `GIT_REPOSITORY` and `GIT_BRANCH`
  RAPIDS.cmake
  README.md
  docs/basics.rst
  rapids-cmake/rapids-version.cmake
Labels: improvement, non-breaking, 3 - Ready for Review

#259 Set `CUDA_USE_STATIC_CUDA_RUNTIME` to control legacy `FindCUDA.cmake`behavior
  rapids-cmake/cuda/init_runtime.cmake
  testing/cuda/init_runtime-multiple.cmake
  testing/cuda/init_runtime-shared.cmake
  testing/cuda/init_runtime-static.cmake
Labels: improvement, non-breaking, 3 - Ready for Review

#267 [FIX] Fix typo in `rapids-cmake-url`
  RAPIDS.cmake
Labels: improvement, non-breaking, 5 - Ready to Merge

#269 Update to Thrust 1.17.2 to fix cub ODR issues
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#264 Support the concept of a patches to apply to a project built via CPM
  cmake-format-rapids-cmake.json
  docs/packages/patches.json
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/cuco.cmake
  rapids-cmake/cpm/detail/display_patch_status.cmake
  rapids-cmake/cpm/detail/generate_patch_command.cmake
  rapids-cmake/cpm/gtest.cmake
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/nvbench.cmake
  rapids-cmake/cpm/package_override.cmake
  rapids-cmake/cpm/patches/command_template.cmake.in
  rapids-cmake/cpm/rmm.cmake
  rapids-cmake/cpm/spdlog.cmake
  rapids-cmake/cpm/thrust.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_generate_patch_command-invalid.cmake
  testing/cpm/cpm_generate_patch_command-override.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#273 Update to CPM 0.35.6 as it has needed changes for cpm patching support.
  rapids-cmake/cpm/detail/download.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#270 rapids_cuda_init_architectures now obeys CUDAARCHS env variable
  rapids-cmake/cuda/init_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-user-via-env.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#271 Correct broken patch_toolkit API docs, and CMake API cross references
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cmake/build_type.cmake
  rapids-cmake/cuda/init_runtime.cmake
  rapids-cmake/cuda/patch_toolkit.cmake
Labels: doc, non-breaking, 3 - Ready for Review

#272 Update to nvcomp 2.4 which now offers aarch64 binaries!
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#276 Restore rapids_cython_create_modules output variable name
  rapids-cmake/cython/create_modules.cmake
Labels: bug, non-breaking, 3 - Ready for Review
