Repository rapidsai/rapids-cmake, pull requests merged in 2022-12, with the labels that each got.

#312 Upgrade spdlog to 1.10.0
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review, Dependencies

#323 Revert "Upgrade spdlog to 1.10.0 (#312)"
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#322 rapids_cuda_init_architectures now supports CUDAARCHS env variable
  rapids-cmake/cuda/init_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-all-via-env.cmake
  testing/cuda/init_arch-native-via-env.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#324 rapids_cuda_patch_toolkit: Better handle non-standard toolkits
  rapids-cmake/cuda/patch_toolkit.cmake
  testing/cuda/patch_toolkit-nested/CMakeLists.txt
  testing/cuda/patch_toolkit-nested/subdir/CMakeLists.txt
  testing/cuda/patch_toolkit.cmake
  testing/find/find_package-cudatoolkit-patching.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#331 Branch 23.02 merge 22.12
  CHANGELOG.md
  dependencies.yaml
Labels: improvement, non-breaking

#329 Update cuco git tag to fetch bug fixes and cleanups
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 5 - Ready to Merge
