Repository rapidsai/rapids-cmake, pull requests merged in 2022-11, with the labels that each got.

#297 Forward merge 22.10 into 22.12
  CHANGELOG.md
Labels: improvement, non-breaking, 3 - Ready for Review

#296 Move libcudacxx 1.8.1 so we support sm90
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#275 Create conda package of patched dependencies
  conda/recipes/rapids_core_dependencies/CMakeLists.txt
  conda/recipes/rapids_core_dependencies/build.sh
  conda/recipes/rapids_core_dependencies/conda_build_config.yaml
  conda/recipes/rapids_core_dependencies/meta.yaml
Labels: feature request, non-breaking

#283 Add GitHub action workflow to rapids-cmake
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/build_cpp.sh
  ci/check_style.sh
  ci/test_cpp.sh
  dependencies.yaml
Labels: feature request, non-breaking

#299 Update cuco to version that supports Ada and Hopper
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#301 Add `ninja` as build dependency
  ci/test_cpp.sh
  conda/recipes/rapids_core_dependencies/meta.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#302 Update cuco git tag
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#305 Remove `rapids-dependency-file-generator` `FIXME`
  ci/check_style.sh
Labels: improvement, non-breaking

#308 Don't use CMake 3.25.0 as it has a show stopping FindCUDAToolkit bug
  conda/recipes/rapids_core_dependencies/meta.yaml
  dependencies.yaml
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#303 Remove usage of FetchContent from tests to improve perf
  testing/utils/project_template.cmake.in
Labels: bug, non-breaking

#311 Fix typo.
  rapids-cmake/cpm/find.cmake
Labels: improvement, non-breaking
