Repository rapidsai/rapids-cmake, pull requests merged in 2022-07, with the labels that each got.

#209 Update nvcomp to 2.3.2
  rapids-cmake/cpm/versions.json
  testing/utils/fill_cache/CMakeLists.txt
Labels: feature request, non-breaking, 3 - Ready for Review

#210 Revert "Update nvcomp to 2.3.2 (#209)"
  rapids-cmake/cpm/versions.json
  testing/utils/fill_cache/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#211 Revert "Revert "Update nvcomp to 2.3.2 (#209)" (#210)"
  rapids-cmake/cpm/versions.json
  testing/utils/fill_cache/CMakeLists.txt
Labels: feature request, non-breaking, 5 - Ready to Merge

#213 Update cuco git tag
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 5 - Ready to Merge

#215 Timestamps for URL downloads match the download time
  rapids-cmake/cpm/detail/get_proprietary_binary.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#214 [FIX] `rapids_find_package()` called with explicit version and REQUIRED should fail
  rapids-cmake/find/package.cmake
  testing/find/CMakeLists.txt
  testing/find/find_package-optional-failed.cmake
  testing/find/find_package-version-explicit-failed.cmake
  testing/find/find_package-version-required-explicit-failed.cmake
Labels: improvement, non-breaking, 3 - Ready for Review

#220 Docs now provide rapids_find_package examples
  rapids-cmake/find/package.cmake
Labels: doc, non-breaking, 3 - Ready for Review

#223 json exclude flag behaves as expected libcudacx//thrust/nvcomp
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/cpm/thrust.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#224 More robust solution of CMake policy 135
  rapids-cmake/cpm/detail/get_proprietary_binary.cmake
  rapids-cmake/cpm/init.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#222 Improve GPU detection by doing less subsequent executions
  rapids-cmake/cuda/detail/detect_architectures.cmake
Labels: feature request, non-breaking, 3 - Ready for Review
