Repository rapidsai/rapids-cmake, pull requests merged in 2022-08, with the labels that each got.

#230 Update to CPM v0.35.3 to support symlink build directories
  rapids-cmake/cpm/detail/download.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#232 Remove incorrect install location note on rapids_export
  rapids-cmake/export/export.cmake
Labels: doc, non-breaking, 3 - Ready for Review

#238 [REVIEW] Use common `js` and defer it
  docs/conf.py
Labels: doc, non-breaking

#221 Update nvcomp to 2.3.3
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review

#236 Update to CPM v0.35.4 for URL downloads match the download time
  rapids-cmake/cpm/detail/download.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#242 Revert "Update to CPM v0.35.4 for URL downloads... (#236)"
  rapids-cmake/cpm/detail/download.cmake
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#231 Update to thrust 1.17
  rapids-cmake/cpm/thrust.cmake
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#241 Docs: RAPIDS.cmake should be placed in current bin dir
  README.md
  docs/basics.rst
  example/CMakeLists.txt
  rapids-cmake/cuda/init_architectures.cmake
Labels: doc, non-breaking, 3 - Ready for Review

#243 Ensure that we install Thrust and Cub correctly.
  rapids-cmake/cpm/thrust.cmake
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#182 put $PREFIX before $BUILD_PREFIX in conda build
  rapids-cmake/cmake/support_conda_env.cmake
  testing/cmake/conda_env-build.cmake
Labels: breaking, bug, 3 - Ready for Review

#244 Patch thrust and cub install rules to have proper header searches
  rapids-cmake/cpm/thrust.cmake
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review

#249 Update to CPM version 0.35.5
  rapids-cmake/cpm/detail/download.cmake
  rapids-cmake/cpm/detail/get_proprietary_binary.cmake
  rapids-cmake/cpm/init.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#250 disable cuco install rules when no INSTALL_EXPORT_SET
  rapids-cmake/cpm/cuco.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_cuco-libcudacxx-no-install-export.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#254 rapids_cpm_thrust record build directory location of thrust-config
  rapids-cmake/cpm/thrust.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#247 Provide suggestions when encountering an incomplete GTest package
  rapids-cmake/cpm/gtest.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_find-gtest-no-gmock/CMakeLists.txt
  testing/cpm/cpm_find-gtest-no-gmock/mock_installed_gtest/include/gtest/gtest.h
  testing/cpm/cpm_find-gtest-no-gmock/mock_installed_gtest/lib/libgtest.so
  testing/cpm/cpm_find-gtest-no-gmock/mock_installed_gtest/lib/libgtest_main.so
Labels: doc, non-breaking, 3 - Ready for Review

#227 Update rapids-cmake to require cmake 3.23.1
  CMakeLists.txt
  example/CMakeLists.txt
  rapids-cmake/cmake/build_type.cmake
  rapids-cmake/cmake/install_lib_dir.cmake
  rapids-cmake/cpm/gtest.cmake
  rapids-cmake/cpm/rmm.cmake
  rapids-cmake/export/detail/parse_version.cmake
  testing/CMakeLists.txt
  testing/cmake/write_git_revision-custom-prefix/CMakeLists.txt
  testing/cmake/write_git_revision-dirty/CMakeLists.txt
  testing/cmake/write_git_revision-embed/CMakeLists.txt
  testing/cmake/write_git_revision-embed/verify_embedding.cmake
  testing/cmake/write_git_revision-no-git/CMakeLists.txt
  testing/cmake/write_git_revision-no-git/verify_embedding.cmake
  testing/cmake/write_git_revision-simple/CMakeLists.txt
  testing/cmake/write_version-absolute/CMakeLists.txt
  testing/cmake/write_version-all-zeroes/CMakeLists.txt
  testing/cmake/write_version-custom-prefix/CMakeLists.txt
  testing/cmake/write_version-leading-zeroes/CMakeLists.txt
  testing/cmake/write_version-relative/CMakeLists.txt
  testing/cpm/cpm_find-add-pkg-source/CMakeLists.txt
  testing/cpm/cpm_find-add-pkg-source/mock_zlib_source_dir/CMakeLists.txt
  testing/cpm/cpm_find-and-find_package/CMakeLists.txt
  testing/cpm/cpm_find-and-find_package/mock_cucxx_source_dir/CMakeLists.txt
  testing/cpm/cpm_find-existing-build-dir/CMakeLists.txt
  testing/cpm/cpm_find-existing-target-to-export-sets/CMakeLists.txt
  testing/cpm/cpm_find-existing-target/CMakeLists.txt
  testing/cpm/cpm_find-options-escaped/CMakeLists.txt
  testing/cpm/cpm_find-options-escaped/rapidstest-config.cmake
  testing/cpm/cpm_find-restore-cpm-vars/CMakeLists.txt
  testing/cpm/cpm_find-restore-cpm-vars/mock_zlib_source_dir/CMakeLists.txt
  testing/cuda/init_arch-all-via-undef/CMakeLists.txt
  testing/cuda/init_arch-native-via-empty-str/CMakeLists.txt
  testing/export/export-verify-build-namespaces/CMakeLists.txt
  testing/export/export-verify-code-block/CMakeLists.txt
  testing/export/export-verify-doc-string/CMakeLists.txt
  testing/export/export-verify-explicit-patch-version-value-of-zero.cmake
  testing/export/export-verify-global-targets/CMakeLists.txt
  testing/export/write_dependencies-multiple-directories/CMakeLists.txt
  testing/export/write_language-multiple-nested-enables/CMakeLists.txt
  testing/export/write_language-nested-dirs/CMakeLists.txt
  testing/find/find_generate_module-build/CMakeLists.txt
  testing/find/find_generate_module-header-only/CMakeLists.txt
  testing/find/find_generate_module-install/CMakeLists.txt
  testing/other/FetchContent-hostile-legacy/CMakeLists.txt
  testing/other/FetchContent-legacy/CMakeLists.txt
  testing/other/rapids_cmake-multiple-cpm/CMakeLists.txt
  testing/other/rapids_cmake-multiple-simple/CMakeLists.txt
  testing/utils/fill_cache/CMakeLists.txt
  testing/utils/project_template.cmake.in
Labels: breaking, feature request, 3 - Ready for Review

#256 Update rapids_find_generate_module to cmake 3.23
  rapids-cmake/find/generate_module.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#253 Update libcudacxx to 1.8
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_libcudacxx-after_cpmfind.cmake
  testing/cpm/cpm_libcudacxx-export.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#258 rapids_cpm_libcudacxx correct location of libcudacxx-config
  rapids-cmake/cpm/libcudacxx.cmake
Labels: bug, non-breaking, 3 - Ready for Review
