Repository rapidsai/rapids-cmake, pull requests merged in 2023-07, with the labels that each got.

#434 When nvcomp is found locally print where it is on disk
  rapids-cmake/cpm/nvcomp.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#435 Bump cuco version
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#437 Update rapids-cmake ci to support conda-forge CUDA 12
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/check_style.sh
  conda/recipes/rapids_core_dependencies/conda_build_config.yaml
  conda/recipes/rapids_core_dependencies/meta.yaml
  dependencies.yaml
Labels: feature request, non-breaking

#438 Migrate to updated shared-action-workflows name for CUDA 12 CI
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#440 Remove trailing comma and add pre-commit hook for JSON validation.
  .pre-commit-config.yaml
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#443 Fix CUDA 11.5 tests by adding dependencies entries.
  dependencies.yaml
Labels: bug, non-breaking

#446 Ensure tests the modify same git repo don't execute at the same time
  testing/cpm/CMakeLists.txt
  testing/test/CMakeLists.txt
  testing/utils/cmake_test.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#448 Use < gcc-11 with cuda 11.5 to avoid nvbench compile failures
  dependencies.yaml
Labels: bug, non-breaking, 3 - Ready for Review

#444 Improve docs around fetch content and rapids-cmake overrides
  rapids-cmake/cpm/find.cmake
  rapids-cmake/cpm/package_override.cmake
Labels: doc, non-breaking
