Repository rapidsai/rapids-cmake, pull requests merged in 2023-12, with the labels that each got.

#498 Upgrade nvCOMP to 3.0.5
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#497 Fix indentation typo
  rapids-cmake/find/generate_module.cmake
Labels: doc, non-breaking

#500 Remove CCCL::Thrust from GLOBAL_TARGETS.
  rapids-cmake/cpm/cccl.cmake
Labels: improvement, non-breaking

#504 Disable NVBench CUPTI support by default.
  rapids-cmake/cpm/nvbench.cmake
  testing/cpm/cpm_nvbench-conda-fmt.cmake
  testing/cpm/cpm_nvbench-conda.cmake
Labels: improvement, non-breaking

#505 Manually invoke install rules for components
  rapids-cmake/cpm/cccl.cmake
  rapids-cmake/cpm/patches/cccl/bug_fixes.diff
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#506 Mark flaky test as serial
  testing/cpm/CMakeLists.txt
Labels: bug, non-breaking

#507 Only apply install rules if we actually downloaded
  rapids-cmake/cpm/cccl.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#494 multiple entry overrides now sets FetchContent for all entries
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/cpm_init-override-multiple.cmake
  testing/cpm/cpm_package_override-obey-cpm-source-var.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#509 Fix docs references to API sections.
  docs/api.rst
  docs/basics.rst
  rapids-cmake/cpm/find.cmake
  rapids-cmake/cpm/package_override.cmake
Labels: doc, non-breaking

#511 Add patch reverting CCCL PR 211.
  rapids-cmake/cpm/patches/cccl/revert_pr_211.diff
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#510 Update cuCollections for CCCL 2.2.0 support.
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#512 Remove scikit-build from dependency list
  dependencies.yaml
Labels: improvement, non-breaking, tech debt

#513 rapids_cpm_cccl preserve install location details from first invocation.
  rapids-cmake/cpm/cccl.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_cccl-preserve-custom-install-loc/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review
