Repository rapidsai/rapids-cmake, pull requests merged in 2023-05, with the labels that each got.

#405 Correct basics to api cross refs
  docs/api.rst
  docs/basics.rst
Labels: doc, non-breaking, 5 - Ready to Merge

#407 Update cuco git tag to support `cuco::static_set`
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#393 rapids_cpm cccl packages cmake files are now relocated to not clash with upstream
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/patches/libcudacxx/install_rules.diff
  rapids-cmake/cpm/thrust.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_libcudacxx-verify-install-custom-libdir/CMakeLists.txt
Labels: breaking, bug, 3 - Ready for Review

#412 Update cuco git tag to fetch several bug fixes
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#413 run docs nightly too
  .github/workflows/build.yaml
  ci/build_docs.sh
Labels: improvement, non-breaking

#403 Use @loader_path instead of $ORIGIN on MacOS
  example/CMakeLists.txt
  rapids-cmake/cython/add_rpath_entries.cmake
  rapids-cmake/cython/create_modules.cmake
Labels: bug, non-breaking, 5 - Ready to Merge

#417 Fea/move to latest nvbench
  rapids-cmake/cpm/patches/nvbench/public_fmt_dep_in_conda.diff
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvbench-conda.cmake
Labels: bug, non-breaking
