Repository rapidsai/rapids-cmake, pull requests merged in 2023-04, with the labels that each got.

#397 Using deprecated CUDA_ARCHITECTURE values now produces an error.
  rapids-cmake/cmake/detail/policy.cmake
  rapids-cmake/cuda/detail/architectures_policy.cmake
  rapids-cmake/cuda/init_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-all-deprecated.cmake
  testing/cuda/init_arch-all-via-env-deprecated.cmake
  testing/cuda/init_arch-all-via-env.cmake
  testing/cuda/init_arch-all.cmake
  testing/cuda/init_arch-existing-project-flags.cmake
  testing/cuda/init_arch-native-via-empty-str-deprecated/CMakeLists.txt
  testing/cuda/init_arch-native-via-empty-str/CMakeLists.txt
  testing/cuda/set_arch-all-deprecated.cmake
  testing/cuda/set_arch-all.cmake
  testing/cuda/set_arch-existing.cmake
Labels: breaking, feature request, 3 - Ready for Review

#398 Update clang-format
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#402 Remove usage of rapids-get-rapids-version-from-git
  ci/build_docs.sh
  ci/release/update-version.sh
Labels: improvement, non-breaking

#401 Upgrade GTest version to 1.13
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#404 Upgrade to Python 3.9 (drop Python 3.9)
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#406 Revert shared workflows branch
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking
