Repository rapidsai/rapids-cmake, pull requests merged in 2023-02, with the labels that each got.

#361 Update shared workflow branches
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/release/update-version.sh
Labels: improvement, non-breaking

#360 Update nvCOMP version to 2.6.1
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#359 Move date to build string in `conda` recipe
  conda/recipes/rapids_core_dependencies/meta.yaml
Labels: improvement, non-breaking

#365 Update shared workflow branches
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#366 Clean up and sort CPM packages.
  cmake-format-rapids-cmake.json
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_gbench-simple.cmake
  testing/cpm/cpm_gtest-simple.cmake
  testing/cpm/cpm_libcudacxx-simple.cmake
  testing/cpm/cpm_nvbench-simple.cmake
  testing/cpm/cpm_nvcomp-invalid-arch.cmake
  testing/cpm/cpm_nvcomp-override-clears-proprietary_binary.cmake
  testing/cpm/cpm_nvcomp-proprietary-off.cmake
  testing/cpm/cpm_nvcomp-proprietary-on.cmake
  testing/cpm/cpm_nvcomp-simple.cmake
  testing/cpm/cpm_rmm-simple.cmake
  testing/cpm/cpm_spdlog-simple.cmake
  testing/cpm/cpm_thrust-simple.cmake
Labels: improvement, non-breaking

#364 Add fmt 9.1.0
  cmake-format-rapids-cmake.json
  docs/api.rst
  docs/packages/rapids_cpm_fmt.rst
  rapids-cmake/cpm/fmt.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_fmt-export.cmake
  testing/cpm/cpm_fmt-simple.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: improvement, non-breaking

#368 Bump spdlog to 1.11, add fmt as dependency for spdlog
  cmake-format-rapids-cmake.json
  rapids-cmake/cpm/spdlog.cmake
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#371 Update to latest nvbench
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#370 Use trap to handle errors in test scripts
  ci/test_cpp.sh
Labels: improvement, non-breaking

#373 Patch nvbench to allow usage of external fmt
  rapids-cmake/cpm/patches/nvbench/use_existing_fmt.diff
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvbench-already-found-fmt.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#347 Add docs build job
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  ci/build_docs.sh
  dependencies.yaml
  docs/conf.py
  rapids-cmake/cython/add_rpath_entries.cmake
  rapids-cmake/cython/create_modules.cmake
Labels: improvement, non-breaking

#374 Update GHAs Workflows
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#375 rapids_cpm_spdlog properly specify usage of external fmt library
  rapids-cmake/cpm/spdlog.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_spdlog-external-fmt.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#378 Introduce clang-format to rapids-cmake to format C++ code examples
  .clang-format
  testing/cmake/write_git_revision-custom-prefix/main.cpp
  testing/cmake/write_git_revision-dirty/main.cpp
  testing/cmake/write_git_revision-embed/main.cpp
  testing/cmake/write_git_revision-no-git/main.cpp
  testing/cmake/write_git_revision-simple/main.cpp
  testing/cmake/write_version-absolute/main.cpp
  testing/cmake/write_version-custom-prefix/main.cpp
  testing/cmake/write_version-relative/main.cpp
  testing/export/write_language-multiple-nested-enables/A/B/D/static.cu
  testing/export/write_language-multiple-nested-enables/A/C/static.cpp
  testing/export/write_language-multiple-nested-enables/A/static.cu
  testing/export/write_language-multiple-nested-enables/main.cpp
  testing/export/write_language-nested-dirs/A/B/static.cu
  testing/export/write_language-nested-dirs/A/static.cu
  testing/export/write_language-nested-dirs/main.cu
Labels: feature request, non-breaking, 3 - Ready for Review

#376 rapids_cpm_nvbench properly specify usage of external fmt library
  dependencies.yaml
  rapids-cmake/cpm/patches/nvbench/public_fmt_dep_in_conda.diff
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvbench-conda-fmt.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#377 proprietary_binary now supports cuda toolkit version placeholders
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/download_proprietary_binary.cmake
  rapids-cmake/cpm/detail/get_proprietary_binary_url.cmake
  rapids-cmake/cpm/nvcomp.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_proprietary-url-ctk-version-find-ctk.cmake
  testing/cpm/cpm_proprietary-url-ctk-version.cmake
  testing/cpm/cpm_proprietary-url-no-ctk-parsing.cmake
  testing/utils/project_template.cmake.in
Labels: feature request, non-breaking, 3 - Ready for Review

#380 Make docs builds less verbose
  ci/build_docs.sh
Labels: improvement, non-breaking
