Repository rapidsai/rapids-cmake, pull requests merged in 2023-06, with the labels that each got.

#418 Remove documentation build scripts for Jenkins
  ci/docs/build.sh
Labels: improvement, non-breaking

#414 Upload conda packages for rapids_core_dependencies.
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  ci/build_cpp.sh
  ci/test_cpp.sh
Labels: improvement, non-breaking

#415 rapids_find_generate_module Support user code blocks
  rapids-cmake/find/generate_module.cmake
  rapids-cmake/find/template/find_module.cmake.in
  testing/find/CMakeLists.txt
  testing/find/find_generate_module-back-final-code-block-var.cmake
  testing/find/find_generate_module-back-initial-code-block-var.cmake
  testing/find/find_generate_module-code-blocks/CMakeLists.txt
  testing/find/find_generate_module-code-blocks/include/rapids-cmake-test-header_only.hpp
Labels: feature request, non-breaking, 3 - Ready for Review

#410 Rewrite of rapids_test_install_relocatable to support genex expressions
  rapids-cmake/test/add.cmake
  rapids-cmake/test/detail/generate_installed_CTestTestfile.cmake
  rapids-cmake/test/detail/record_test_command.cmake
  rapids-cmake/test/detail/record_test_component.cmake
  rapids-cmake/test/install_relocatable.cmake
  testing/test/CMakeLists.txt
  testing/test/add-with-install-component.cmake
  testing/test/install_relocatable-include-in-all.cmake
  testing/test/install_relocatable-labels.cmake
  testing/test/install_relocatable-simple.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#358 Make NAMESPACE property truly optional in rapids_export
  ci/test_cpp.sh
  rapids-cmake/export/detail/component.cmake
  rapids-cmake/export/export.cmake
  rapids-cmake/export/template/config.cmake.in
  testing/export/CMakeLists.txt
  testing/export/export-verify-no-namespace/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#420 test_install_relocatable correct run_gpu_test.cmake location
  rapids-cmake/test/detail/generate_installed_CTestTestfile.cmake
  rapids-cmake/test/install_relocatable.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#425 Fix google benchmark name and update version
  rapids-cmake/cpm/gbench.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_gbench-export.cmake
Labels: improvement, non-breaking

#423 Correct install_relocatable issues found by libcudf
  rapids-cmake/test/detail/generate_installed_CTestTestfile.cmake
  rapids-cmake/test/install_relocatable.cmake
  testing/test/CMakeLists.txt
  testing/test/install_relocatable-complex/CMakeLists.txt
  testing/test/install_relocatable-complex/tests/CMakeLists.txt
  testing/test/install_relocatable-complex/usage.cu
Labels: bug, non-breaking, 3 - Ready for Review

#428 support_conda_env support host and build CTK 12 locations
  rapids-cmake/cmake/support_conda_env.cmake
  testing/cmake/CMakeLists.txt
  testing/cmake/conda_env-cross-build-arm.cmake
  testing/cmake/conda_env-cross-build-x86.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#430 Bug/proprietary binary obeys `always_download`
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/package_details.cmake
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/find/package.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#432 Correct two issues found when testing CMake 3.27 rc2
  rapids-cmake/cpm/rmm.cmake
  rapids-cmake/cpm/thrust.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#429 Add rapids_cuda_set_runtime
  cmake-format-rapids-cmake.json
  docs/api.rst
  docs/command/rapids_cuda_set_runtime.rst
  rapids-cmake/cuda/set_runtime.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/set_runtime-on-interface-target.cmake
  testing/cuda/set_runtime-shared.cmake
  testing/cuda/set_runtime-static.cmake
Labels: feature request, non-breaking

#431 Correct re-root controls from conda-forge with thrust/cub/etc
  rapids-cmake/cpm/patches/Thrust/reroot_support.diff
  rapids-cmake/cpm/patches/libcudacxx/reroot_support.diff
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review
