Repository rapidsai/rapids-cmake, pull requests merged in 2023-09, with the labels that each got.

#456 Support fmt use in debug builds
  rapids-cmake/cpm/patches/fmt/no_debug_warnings.diff
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#457 Use `conda mambabuild` not `mamba mambabuild`
  ci/build_cpp.sh
  dependencies.yaml
Labels: bug, non-breaking

#459 Update to clang 16.0.6.
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#458 cpm overrides don't occur when `CPM_<pkg>_SOURCE` exists
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_package_override-obey-cpm-source-var.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#460 Update to CPM v0.38.5
  rapids-cmake/cpm/detail/download.cmake
Labels: improvement, non-breaking, 3 - Ready for Review

#462 Move rapids_cpm_package_override to CPM section of docs
  docs/api.rst
Labels: doc, non-breaking, 5 - Ready to Merge

#461 Update image names
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
Labels: improvement, non-breaking

#463 Quote the list of patch files in case they have spaces in their paths
  rapids-cmake/cpm/patches/command_template.cmake.in
  testing/cpm/cpm_generate_patch_command-current_json_dir.cmake
Labels: bug, non-breaking
