Repository rapidsai/rapids-cmake, pull requests merged in 2023-01, with the labels that each got.

#330 Update conda recipes.
  .github/workflows/pr.yaml
  conda/recipes/rapids_core_dependencies/meta.yaml
Labels: improvement, non-breaking, conda

#335 rapids-cmake now errors out when CPM can't be downloaded
  rapids-cmake/cpm/detail/download.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#332 Update to libcudacxx 1.9 to match version found in CUDA Toolkit 12
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#337 Revert update of libcudacxx 1.9
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#336 Use pre-commit for style checks
  .pre-commit-config.yaml
  ci/check_style.sh
  ci/checks/copyright.py
  ci/checks/run-cmake-format.sh
  dependencies.yaml
Labels: improvement, non-breaking

#338 Add codespell and whitespace linters to pre-commit hooks.
  .pre-commit-config.yaml
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTING.md
  docs/api.rst
  docs/command/rapids_cython_init.rst
  docs/dependency_tracking.rst
  docs/packages/rapids_cpm_versions.rst
  example/CMakeLists.txt
  init.cmake
  rapids-cmake/cmake/install_lib_dir.cmake
  rapids-cmake/cmake/parse_version.cmake
  rapids-cmake/cmake/support_conda_env.cmake
  rapids-cmake/cmake/write_git_revision_file.cmake
  rapids-cmake/cpm/find.cmake
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/export/cpm.cmake
  rapids-cmake/export/export.cmake
  rapids-cmake/export/write_dependencies.cmake
  rapids-cmake/export/write_language.cmake
  rapids-cmake/find/generate_module.cmake
  rapids-cmake/find/package.cmake
  setup.cfg
  testing/CMakeLists.txt
  testing/cmake/conda_env-invalid.cmake
  testing/cmake/parse_version-major-valid.cmake
  testing/cmake/write_git_revision-dirty/CMakeLists.txt
  testing/cmake/write_git_revision-embed/verify_embedding.cmake
  testing/cmake/write_git_revision-no-git/verify_embedding.cmake
  testing/cpm/cpm_find-and-find_package/CMakeLists.txt
  testing/cpm/cpm_find-components/CMakeLists.txt
  testing/cpm/cpm_find-options-escaped/CMakeLists.txt
  testing/cpm/cpm_find-version-explicit-install.cmake
  testing/cpm/cpm_init-override-simple.cmake
  testing/cpm/cpm_libcudacxx-after_cpmfind.cmake
  testing/cpm/cpm_package_override-before-init.cmake
  testing/cpm/rapids-cpm.cmake
  testing/cuda/init_arch-user-via-env.cmake
  testing/cuda/init_arch-user.cmake
  testing/export/export-verify-build-namespaces/CMakeLists.txt
  testing/export/export-verify-code-block/CMakeLists.txt
  testing/export/export-verify-doc-string/CMakeLists.txt
  testing/export/export-verify-global-targets/CMakeLists.txt
  testing/export/export-verify-version.cmake
  testing/export/export_cpm-options-escaped.cmake
  testing/export/export_package-build-with-components-and-version.cmake
  testing/export/export_package-build-with-components.cmake
  testing/export/export_package-build-with-empty-components.cmake
  testing/export/export_package-build-with-version.cmake
  testing/export/export_package-install.cmake
  testing/export/write_dependencies-cpm-preserve-options.cmake
  testing/export/write_dependencies-root-dirs.cmake
  testing/find/find_package-components/CMakeLists.txt
  testing/find/find_package-version-explicit.cmake
  testing/find/find_package-version-none.cmake
  testing/utils/setup_cpm_cache.cmake
Labels: improvement, non-breaking

#333 Update to nvcomp 2.5
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#340 Make generated find module targets global
  rapids-cmake/find/template/find_module.cmake.in
  testing/find/find_generate_module-install/CMakeLists.txt
Labels: improvement, non-breaking, 3 - Ready for Review

#339 Add deprecation warnings for usage of `ALL`
  cmake-format-rapids-cmake.json
  rapids-cmake/cmake/detail/policy.cmake
  rapids-cmake/cuda/detail/architectures_policy.cmake
  rapids-cmake/cuda/init_architectures.cmake
  rapids-cmake/cuda/set_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-all-deprecated.cmake
  testing/cuda/init_arch-all-via-env-deprecated.cmake
  testing/cuda/set_arch-all-deprecated.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#341 Update to nvcomp 2.6
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#343 Update to libcudacxx 1.9.1 to have a version >= CUDA Toolkit 12
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#342 Update spdlog to 1.11 ( latest version )
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#344 Build against CUDA `11.8`
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  ci/test_cpp.sh
  dependencies.yaml
Labels: improvement, non-breaking

#346 Revert "Update spdlog to 1.11 ( latest version ) (#342)"
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#345 Add deprecation notice to passing "" to CMAKE_CUDA_ARCHITECTURES
  rapids-cmake/cuda/detail/architectures_policy.cmake
  rapids-cmake/cuda/init_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-native-via-empty-str-deprecated/CMakeLists.txt
Labels: feature request, non-breaking, 3 - Ready for Review

#351 Use string literals for policy test messages so no escaping needed
  testing/cuda/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#353 cpm: `always_download` now considers `patches` json entry
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/package_details.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_package_override-patches.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#355 Remove incorrect deprecation for CMAKE_CUDA_ARCHITECTURES="NATIVE"
  rapids-cmake/cuda/init_architectures.cmake
  testing/cuda/init_arch-all-via-env-deprecated.cmake
  testing/cuda/init_arch-all-via-env.cmake
  testing/cuda/init_arch-all.cmake
  testing/cuda/init_arch-native-via-env.cmake
  testing/cuda/init_arch-native.cmake
  testing/cuda/init_arch-rapids-via-env.cmake
Labels: bug, non-breaking, ! - Hotfix, 3 - Ready for Review
