Repository rapidsai/rapids-cmake, pull requests merged in 2023-10, with the labels that each got.

#468 Build CUDA 12.0 ARM conda packages.
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  RAPIDS.cmake
  rapids-cmake/cuda/detail/invoke_set_all_architectures.cmake
  rapids-cmake/rapids-version.cmake
  testing/cuda/init_arch-all-via-undef/CMakeLists.txt
  testing/cuda/init_arch-rapids.cmake
  testing/cuda/set_arch-rapids.cmake
  testing/cuda/validate-cuda-rapids.cmake
Labels: improvement, non-breaking

#470 Express Python version in dependencies.yaml.
  dependencies.yaml
Labels: improvement, non-breaking

#472 Use branch-23.12 workflows.
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#464 Update libcudacxx to 2.1.0
  rapids-cmake/cpm/patches/command_template.cmake.in
  rapids-cmake/cpm/patches/libcudacxx/install_rules.diff
  rapids-cmake/cpm/patches/libcudacxx/proclaim_return_type_nv_exec_check_disable.diff
  rapids-cmake/cpm/patches/libcudacxx/reroot_support.diff
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#474 target from write_git_revision now works with export sets
  rapids-cmake/cmake/write_git_revision_file.cmake
  testing/cmake/write_git_revision-simple/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#476 Add patch for libcudacxx memory resource.
  rapids-cmake/cpm/patches/libcudacxx/memory_resource.diff
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#477 GTest will always be PIC enabled when built
  rapids-cmake/cpm/gtest.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_gtest-static.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#479 Update cuco git tag
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 5 - Ready to Merge
