Repository rapidsai/rapids-cmake, pull requests merged in 2023-11, with the labels that each got.

#480 Allow rapids_test to be used without CUDAToolkit
  rapids-cmake/test/detail/generate_resource_spec.cpp
  rapids-cmake/test/generate_resource_spec.cmake
  testing/test/CMakeLists.txt
  testing/test/add-no-cuda-toolkit/CMakeLists.txt
  testing/test/add-no-cuda-toolkit/main.cpp
Labels: feature request, non-breaking, 3 - Ready for Review

#451 Upgrade nvCOMP to 3.0.4
  rapids-cmake/cpm/versions.json
Labels: breaking, feature request

#483 Remove invalid argument to find_package_root
  rapids-cmake/cpm/libcudacxx.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#484 Remove deprecated function usages
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/find/generate_module.cmake
  testing/export/write_dependencies-root-dirs.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#482 Drop Pascal architecture (60).
  rapids-cmake/cuda/set_architectures.cmake
  testing/cuda/validate-cuda-rapids.cmake
Labels: breaking, improvement

#486 Ensure nvbench initializes nvml context when built statically
  rapids-cmake/cpm/patches/nvbench/nvml_with_static_builds.diff
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#490 Build concurrency for nightly and merge triggers
  .github/workflows/build.yaml
Labels: improvement, non-breaking

#488 Move to latest nvbench which has nvml+static support
  rapids-cmake/cpm/patches/nvbench/nvml_with_static_builds.diff
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#473 Update to spdlog 1.12 and fmt 10.1.1
  rapids-cmake/cpm/patches/fmt/no_debug_warnings.diff
  rapids-cmake/cpm/patches/spdlog/nvcc_constexpr_fix.diff
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking
