Repository rapidsai/rapids-cmake, pull requests merged in 2024-06, with the labels that each got.

#607 Update CCCL to v2.5.0
  CHANGELOG.md
  rapids-cmake/cpm/patches/cccl/bug_fixes.diff
  rapids-cmake/cpm/patches/cccl/hide_kernels.diff
  rapids-cmake/cpm/patches/cccl/kernel_pointer_hiding.diff
  rapids-cmake/cpm/patches/cccl/revert_pr_211.diff
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_generate_pins-nested/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple-via-variable/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple/CMakeLists.txt
  testing/cpm/cpm_generate_pins-var-and-arg/CMakeLists.txt
Labels: breaking, feature request

#629 Adopt CI/packaging codeowners
  .github/CODEOWNERS
Labels: improvement, non-breaking

#624 Eval CMAKE_CUDA_ARCHITECTURES before ENV{CUDAARCHS}
  rapids-cmake/cuda/detail/architectures_policy.cmake
  rapids-cmake/cuda/init_architectures.cmake
  rapids-cmake/cuda/set_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-all-via-env-deprecated.cmake
  testing/cuda/init_arch-native-via-env.cmake
  testing/cuda/init_arch-native.cmake
  testing/cuda/init_arch-rapids-via-env.cmake
  testing/cuda/init_arch-var-over-env.cmake
  testing/cuda/set_arch-all-deprecated.cmake
  testing/cuda/validate-cuda-native.cmake
  testing/cuda/validate-cuda-rapids.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#631 Bump CCCL version to include cuda::std::span fix
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#635 rapids_cmake_support_conda_env adds `-O0` to debug compile lines
  rapids-cmake/cmake/support_conda_env.cmake
  testing/cmake/conda_env-build.cmake
  testing/cmake/conda_env-prefix.cmake
Labels: feature request, non-breaking, 3 - Ready for Review
