Repository rapidsai/rapids-cmake, pull requests merged in 2024-02, with the labels that each got.

#531 add rapids-dependency-file-generator pre-commit hook
  .pre-commit-config.yaml
Labels: bug, non-breaking, 3 - Ready for Review

#533 Error out if generate_ctest_json fails to build or run
  rapids-cmake/test/detail/generate_installed_CTestTestfile.cmake
  rapids-cmake/test/generate_resource_spec.cmake
  testing/test/install_relocatable-complex/tests/CMakeLists.txt
  testing/test/install_relocatable-include-in-all.cmake
  testing/test/install_relocatable-simple.cmake
Labels: bug, non-breaking

#535 Ensure that `ctest` is called with `--no-tests=error`.
  ci/test_cpp.sh
Labels: improvement, non-breaking

#538 Add rapids_cuda_set_runtime to default includes of cuda
  rapids-cmake/rapids-cuda.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#521 Support CUDA 12.2
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  conda/recipes/rapids_core_dependencies/meta.yaml
  dependencies.yaml
Labels: feature request, non-breaking, conda

#526 Fetch the latest cuco and remove outdated patches
  rapids-cmake/cpm/patches/cuco/hide_kernels.diff
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#540 Officially support env var expansion in version.json
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/detail/package_details.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_package_override-env-var-support.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#541 target branch-24.04 for GitHub Actions workflows
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#542 Bump to nvcomp 3.0.6.
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#537 Build generate_ctest_json in try_compile()
  rapids-cmake/test/detail/generate_resource_spec/CMakeLists.txt
  rapids-cmake/test/detail/generate_resource_spec/generate_resource_spec.cpp
  rapids-cmake/test/generate_resource_spec.cmake
Labels: improvement, non-breaking

#545 Forward-merge branch-24.02 to branch-24.04
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#544 Remove unneeded whitespace from json
  .pre-commit-config.yaml
  ci/checks/cmake_config_lint.json
  ci/checks/cmake_config_testing_lint.json
  cmake-format-rapids-cmake.json
  docs/packages/example.json
  docs/packages/patches.json
  docs/packages/proprietary_binary.json
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_generate_patch_command-current_json_dir.cmake
  testing/cpm/cpm_generate_patch_command-override.cmake
  testing/cpm/cpm_generate_patch_command-verify-copyright-header.cmake
  testing/cpm/cpm_init-override-multiple.cmake
  testing/cpm/cpm_init-override-simple.cmake
  testing/cpm/cpm_nvcomp-override-clears-proprietary_binary.cmake
  testing/cpm/cpm_package_override-before-init.cmake
  testing/cpm/cpm_package_override-empty.cmake
  testing/cpm/cpm_package_override-env-var-support.cmake
  testing/cpm/cpm_package_override-multiple.cmake
  testing/cpm/cpm_package_override-obey-cpm-source-var.cmake
  testing/cpm/cpm_package_override-patches.cmake
  testing/cpm/cpm_package_override-simple.cmake
  testing/cpm/cpm_proprietary-url-ctk-version-find-ctk.cmake
  testing/cpm/cpm_proprietary-url-ctk-version.cmake
  testing/cpm/cpm_proprietary-url-no-ctk-parsing.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#547 Add support for Python 3.11
  dependencies.yaml
Labels: improvement, non-breaking
