Repository rapidsai/rapids-cmake, pull requests merged in 2024-03, with the labels that each got.

#549 Bump nvbench version for faster benchmark runs
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#555 Support getting rapids-cmake via git clone
  RAPIDS.cmake
  README.md
  testing/other/CMakeLists.txt
  testing/other/rapids_cmake-fetch-via-git/CMakeLists.txt
  testing/other/rapids_cmake-fetch-via-zip/CMakeLists.txt
Labels: feature request, non-breaking, 3 - Ready for Review

#560 Deprecate rapids_cpm_libcudacxx and rapids_cpm_thrust.
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/thrust.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#559 rapids-cmake support empty patches array in json
  rapids-cmake/cpm/detail/generate_patch_command.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_package_override-empty-patches.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#557 Handle CMake 3.28 new EXCLUDE_FROM_ALL option of `FetchContent`
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_package_override-add-new-project.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#561 Use CUDA compiler if available for generate_resource_spec
  rapids-cmake/test/generate_resource_spec.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#556 Replace local copyright check with pre-commit-hooks verify-copyright
  .pre-commit-config.yaml
  ci/checks/copyright.py
Labels: improvement, non-breaking

#548 Add patch to fix fmt `v10.1.1` version
  rapids-cmake/cpm/patches/fmt/fix_10_1_1_version.diff
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review

#563 Forward-merge branch-24.04 to branch-24.06
  .pre-commit-config.yaml
  ci/checks/copyright.py
  rapids-cmake/cpm/patches/fmt/fix_10_1_1_version.diff
  rapids-cmake/cpm/versions.json
  rapids-cmake/test/generate_resource_spec.cmake
Labels: improvement, non-breaking

#564 Always link against cudart_static
  rapids-cmake/test/detail/generate_resource_spec/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#570 nvcomp try proprietary binary when 'always_download' is on
  rapids-cmake/cpm/nvcomp.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvcomp-always-download-proprietary_binary.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#573 Use `conda env create --yes` instead of `--force`
  ci/build_docs.sh
  ci/check_style.sh
  ci/test_cpp.sh
Labels: improvement, non-breaking
