Repository rapidsai/rapids-cmake, pull requests merged in 2024-09, with the labels that each got.

#688 Add support for Python 3.12
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#633 Upgrade nvcomp to 4.0.1
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_nvcomp-proprietary_binary-lib-location-common.cmake
Labels: feature request, non-breaking

#691 Use CI workflow branch 'branch-24.10' again
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#692 Add INSTALL_TARGET argument to rapids_add_test()
  rapids-cmake/test/add.cmake
  testing/test/CMakeLists.txt
  testing/test/add-with-install-target-missing.cmake
  testing/test/add-with-install-target.cmake
Labels: improvement, non-breaking

#689 update fmt (to 11.0.2) and spdlog (to 1.14.1)
  dependencies.yaml
  rapids-cmake/cpm/patches/fmt/fix_10_1_1_version.diff
  rapids-cmake/cpm/patches/fmt/fix_11_0_2_unreachable_loop.diff
  rapids-cmake/cpm/patches/spdlog/nvcc_constexpr_fix.diff
  rapids-cmake/cpm/versions.json
Labels: breaking, improvement
