Repository rapidsai/rapids-cmake, pull requests merged in 2024-05, with the labels that each got.

#595 Expand rapids_cpm_init to support custom default version files
  cmake-format-rapids-cmake.json
  rapids-cmake/cpm/detail/load_preset_versions.cmake
  rapids-cmake/cpm/init.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_init-bad-default-path.cmake
  testing/cpm/cpm_init-custom-default-multiple.cmake
  testing/cpm/cpm_init-custom-default-simple.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#599 limit pinning tests to CPM-downloaded projects
  testing/cpm/cpm_generate_pins-nested/CMakeLists.txt
  testing/cpm/cpm_generate_pins-nested/verify/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple/verify/CMakeLists.txt
Labels: improvement, non-breaking

#596 Allow for cpm default and override files via variables
  rapids-cmake/cpm/detail/load_preset_versions.cmake
  rapids-cmake/cpm/init.cmake
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_init-bad-default-cmake-var.cmake
  testing/cpm/cpm_init-bad-override-cmake-var.cmake
  testing/cpm/cpm_init-custom-default-via-cmake-var.cmake
  testing/cpm/cpm_init-override-via-cmake-var.cmake
Labels: feature request, non-breaking

#594 Migrate to `{{ stdlib("c") }}`
  conda/recipes/rapids_core_dependencies/conda_build_config.yaml
  conda/recipes/rapids_core_dependencies/meta.yaml
Labels: improvement, non-breaking, conda

#597 Correctly set the install location for nvcomp when using the proprietary binary
  rapids-cmake/cpm/nvcomp.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvcomp-proprietary_binary-lib-location.cmake
Labels: bug, non-breaking

#602 Ensure nvcomps build and install layouts are consistent
  rapids-cmake/cpm/nvcomp.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvcomp-proprietary_binary-lib-location.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#601 Refactor the common `verify` cpm pin test logic to a single source
  testing/cpm/cpm_generate_pins-nested/CMakeLists.txt
  testing/cpm/cpm_generate_pins-nested/verify/CMakeLists.txt
  testing/cpm/cpm_generate_pins-no-src-dir/CMakeLists.txt
  testing/cpm/cpm_generate_pins-pure-cpm/CMakeLists.txt
  testing/cpm/cpm_generate_pins-pure-cpm/verify/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple/verify/CMakeLists.txt
  testing/cpm/verify_generated_pins.cmake
  testing/cpm/verify_generated_pins/CMakeLists.txt
Labels: feature request, non-breaking, Refactor

#600 rapids-cmake allow GENERATE_PINNED_VERSIONS via CMake variable
  rapids-cmake/cpm/init.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple-via-variable/CMakeLists.txt
  testing/cpm/cpm_generate_pins-var-and-arg/CMakeLists.txt
Labels: feature request, non-breaking, 3 - Ready for Review

#604 Support CMAKE_INSTALL_MESSAGE + rapids_test_install_relocatable
  rapids-cmake/test/detail/generate_installed_CTestTestfile.cmake
  testing/test/CMakeLists.txt
  testing/test/install_relocatable-installed-tests-run-lazy-msg/CMakeLists.txt
  testing/test/install_relocatable-installed-tests-run-lazy-msg/main.cu
  testing/test/install_relocatable-installed-tests-run/CMakeLists.txt
  testing/test/install_relocatable-installed-tests-run/main.cu
Labels: bug, non-breaking, 3 - Ready for Review

#606 Add rapids_cpm_nvtx3.
  docs/api.rst
  docs/packages/rapids_cpm_nvtx3.rst
  rapids-cmake/cpm/nvtx3.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvtx-build-config-works.cmake
  testing/cpm/cpm_nvtx-export.cmake
  testing/cpm/cpm_nvtx-install-config-works.cmake
  testing/cpm/cpm_nvtx-simple.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: feature request, non-breaking

#609 Output what cuda archs rapids-cmake is building for
  rapids-cmake/cuda/set_architectures.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#615 Fix `nvtx3` build export
  rapids-cmake/cpm/nvtx3.cmake
  rapids-cmake/export/package.cmake
  testing/cpm/cpm_nvtx-export.cmake
Labels: improvement, non-breaking, 3 - Ready for Review

#617 Always offer the install target names for nvtx3
  rapids-cmake/cpm/nvtx3.cmake
  testing/cpm/cpm_nvtx-build-config-works.cmake
  testing/cpm/cpm_nvtx-install-config-works.cmake
  testing/cpm/cpm_nvtx-simple.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#619 set_architectures output correct CUDA arch values for RAPIDS mode
  rapids-cmake/cuda/set_architectures.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#614 Removes legacy rapids-cmake cython implementations as it is deprecated in 24.08
  docs/api.rst
  docs/command/rapids_cython_add_rpath_entries.rst
  docs/command/rapids_cython_create_modules.rst
  docs/command/rapids_cython_init.rst
  rapids-cmake/cython/add_rpath_entries.cmake
  rapids-cmake/cython/create_modules.cmake
  rapids-cmake/cython/detail/skbuild_patches.cmake
  rapids-cmake/cython/detail/verify_init.cmake
  rapids-cmake/cython/init.cmake
  rapids-cmake/rapids-cython.cmake
  testing/CMakeLists.txt
  testing/cython/CMakeLists.txt
  testing/cython/cython_add_rpath_entries/CMakeLists.txt
  testing/cython/cython_add_rpath_entries/test.pyx
  testing/cython/cython_create_modules/CMakeLists.txt
  testing/cython/cython_create_modules/test.pyx
  testing/cython/cython_create_modules_errors.cmake
  testing/cython/cython_create_modules_with_library/CMakeLists.txt
  testing/cython/cython_create_modules_with_library/test.pyx
  testing/cython/cython_create_modules_with_prefix/CMakeLists.txt
  testing/cython/cython_create_modules_with_prefix/test.pyx
  testing/cython/cython_init.cmake
  testing/cython/rapids-cython.cmake
Labels: breaking, feature request, 3 - Ready for Review

#613 expand rapids-cmake cpm docs
  docs/api.rst
  docs/cpm.rst
  docs/index.rst
  docs/packages/example_all_fields.json
  docs/packages/example_git_tag_override.json
  docs/packages/example_new_project_override.json
  docs/packages/packages.rst
  docs/packages/rapids_cpm_versions.rst
  rapids-cmake/cpm/package_override.cmake
Labels: doc, non-breaking

#621 Only output CUDA architectures we are building for once
  rapids-cmake/cuda/detail/detect_architectures.cmake
  rapids-cmake/cuda/set_architectures.cmake
Labels: bug, non-breaking, 3 - Ready for Review
