Repository rapidsai/rapids-cmake, pull requests merged in 2024-07, with the labels that each got.

#636 rapids_test_install_relocatable now handles SOVERSION target properties
  rapids-cmake/test/detail/generate_installed_CTestTestfile.cmake
  testing/test/install_relocatable-complex/CMakeLists.txt
  testing/test/install_relocatable-complex/tests/CMakeLists.txt
Labels: bug, non-breaking, 3 - Ready for Review

#639 Try any failing tests up to 3 times to guard against network issues
  ci/test_cpp.sh
Labels: feature request, non-breaking

#637 Fix CPM package docs.
  .github/CODEOWNERS
  docs/api.rst
  docs/cpm.rst
  docs/packages/packages.rst
Labels: doc, non-breaking

#641 Set CUDA_RUNTIME_LIBRARY to documented case style
  rapids-cmake/cuda/set_runtime.cmake
  testing/cuda/set_runtime-shared.cmake
  testing/cuda/set_runtime-static.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#640 Remove CCCL patch for PR 211.
  rapids-cmake/cpm/patches/cccl/revert_pr_211.diff
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_find-patch-command/CMakeLists.txt
  testing/cpm/cpm_find-patch-command/override.json
  testing/cpm/cpm_find-patch-command/patches/0001-move-git-sha1.patch
  testing/cpm/cpm_find-patch-command/patches/0002-move-git-sha1-a-second-time.patch
Labels: feature request, non-breaking

#628 Update cuco git tag to fetch new multiset data structure
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#642 Update to CPM v0.40.0
  rapids-cmake/cpm/detail/download.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#644 Fetch the latest cuco with CAS fixes
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 2 - In Progress

#646 use latest cuco with insert_or_apply CAS fix
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 5 - Ready to Merge

#647 Use workflow branch 24.08 again
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#648 proprietary_binary_cuda_version_mapping allows for better CUDA version mapping
  docs/cpm.rst
  docs/packages/cuda_version_mapping.json
  rapids-cmake/cpm/detail/get_proprietary_binary_url.cmake
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#645 generate_resource_spec uses the enabled languages to determine compiler
  rapids-cmake/test/generate_resource_spec.cmake
Labels: bug, non-breaking

#651 Add rapids_cpm_bs_thread_pool()
  cmake-format-rapids-cmake.json
  docs/packages/packages.rst
  docs/packages/rapids_cpm_bs_thread_pool.rst
  rapids-cmake/cpm/bs_thread_pool.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_bs_thread_pool-build-config-works.cmake
  testing/cpm/cpm_bs_thread_pool-export.cmake
  testing/cpm/cpm_bs_thread_pool-install-config-works.cmake
  testing/cpm/cpm_bs_thread_pool-simple.cmake
Labels: feature request, non-breaking

#652 Add rapids_cpm_nvtx3 to cmake-format-rapids-cmake.json
  cmake-format-rapids-cmake.json
  rapids-cmake/cpm/nvtx3.cmake
Labels: bug, non-breaking

#655 Pass `GLOBAL_TARGETS` to `rapids_cpm_find()` in `rapids_cpm_bs_thread_pool()`
  rapids-cmake/cpm/bs_thread_pool.cmake
  testing/cpm/cpm_bs_thread_pool-simple.cmake
Labels: bug, non-breaking, 5 - Ready to Merge

#659 Use `CMAKE_CUDA_ARCHITECTURES` value when ENV{CUDAARCHS} is set
  rapids-cmake/cuda/init_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-user-over-env.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#662 bs_thread_pool uses C++ 17
  rapids-cmake/cpm/bs_thread_pool.cmake
Labels: bug, non-breaking
