Repository rapidsai/rapids-cmake, pull requests merged in 2024-11, with the labels that each got.

#708 Warn when override of a default package uses the incorrect case
  rapids-cmake/cpm/detail/get_default_json.cmake
  rapids-cmake/cpm/detail/get_override_json.cmake
  rapids-cmake/cpm/detail/load_preset_versions.cmake
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_package_override-defaults-with-different-casing-warning.cmake
  testing/cpm/cpm_package_override-defaults-with-different-casing.cmake
Labels: feature request, non-breaking

#715 Search for the normalized package name when patching
  rapids-cmake/cpm/detail/generate_patch_command.cmake
Labels: bug, non-breaking

#712 rapids_export_write_language no longer generates cmake dev warnings
  rapids-cmake/export/write_language.cmake
  testing/cpm/CMakeLists.txt
  testing/test/CMakeLists.txt
  testing/utils/cmake_test.cmake
Labels: bug, non-breaking

#716 Verifies that current_json_dir placeholder works with normalized package names
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_generate_patch_command-override-case-insensitive.cmake
Labels: feature request, non-breaking

#719 Add breaking change workflow trigger
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking
