Repository rapidsai/rapids-cmake, pull requests merged in 2024-10, with the labels that each got.

#698 Bump cuco version to fetch the Hyperloglog renaming
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#700 version.json patch command supports required field
  docs/cpm.rst
  rapids-cmake/cpm/detail/display_patch_status.cmake
  rapids-cmake/cpm/detail/generate_patch_command.cmake
  rapids-cmake/cpm/patches/command_template.cmake.in
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-required-fails/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-required-fails/override.json
  testing/cpm/cpm_find-patch-command-required-fails/patches/0001-move-git-sha1.patch
  testing/cpm/cpm_find-patch-command-required-fails/patches/0002-bad-git-change.patch
  testing/cpm/cpm_find-patch-command-required/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-required/override.json
  testing/cpm/cpm_find-patch-command-required/patches/0001-move-git-sha1.patch
  testing/cpm/cpm_find-patch-command-required/patches/0002-move-git-sha1-a-second-time.patch
Labels: feature request, non-breaking

#705 Fix docs warning about get_html_theme_path.
  docs/conf.py
Labels: doc, non-breaking

#707 Bump cuco version to fetch the new multiset retrieve
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review

#709 Upgrade nvcomp to 4.1.0.6
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking
