Repository rapidsai/rapids-cmake, pull requests merged in 2024-01, with the labels that each got.

#515 rapids cpm patches now support differences in white space.
  rapids-cmake/cpm/patches/command_template.cmake.in
Labels: feature request, non-breaking, 3 - Ready for Review

#516 Add link libraries to generate_resource_spec cmake
  rapids-cmake/test/generate_resource_spec.cmake
Labels: bug, non-breaking, 5 - Ready to Merge

#520 Fix message context
  rapids-cmake/cython-core/init.cmake
  rapids-cmake/cython/init.cmake
Labels: bug, non-breaking

#517 refactor CUDA versions in dependencies.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#524 Remove usages of rapids-env-update
  ci/build_cpp.sh
Labels: improvement, non-breaking, 3 - Ready for Review

#525 Always download repos when they are being patched
  rapids-cmake/cpm/cccl.cmake
  rapids-cmake/cpm/cuco.cmake
  rapids-cmake/cpm/detail/generate_patch_command.cmake
  rapids-cmake/cpm/find.cmake
  rapids-cmake/cpm/fmt.cmake
  rapids-cmake/cpm/gbench.cmake
  rapids-cmake/cpm/gtest.cmake
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/nvbench.cmake
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/cpm/package_override.cmake
  rapids-cmake/cpm/rmm.cmake
  rapids-cmake/cpm/spdlog.cmake
  rapids-cmake/cpm/thrust.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_find-patch-command/CMakeLists.txt
Labels: bug, non-breaking

#523 Mark all cccl and cuco kernels with hidden visibility
  rapids-cmake/cpm/cccl.cmake
  rapids-cmake/cpm/patches/cccl/hide_kernels.diff
  rapids-cmake/cpm/patches/cuco/hide_kernels.diff
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#527 rapids_cpm_cccl now works as expected when given `DOWNLOAD_ONLY ON`
  rapids-cmake/cpm/cccl.cmake
Labels: bug, non-breaking, 3 - Ready for Review
