Repository rapidsai/rapids-cmake, pull requests merged in 2024-08, with the labels that each got.

#665 Remove 24.10 deprecated commands
  cmake-format-rapids-cmake.json
  docs/api.rst
  docs/command/rapids_cuda_patch_toolkit.rst
  docs/packages/packages.rst
  docs/packages/rapids_cpm_libcudacxx.rst
  docs/packages/rapids_cpm_thrust.rst
  rapids-cmake/cpm/libcudacxx.cmake
  rapids-cmake/cpm/patches/Thrust/install_rules.diff
  rapids-cmake/cpm/patches/Thrust/reroot_support.diff
  rapids-cmake/cpm/patches/Thrust/transform_iter_with_reduce_by_key.diff
  rapids-cmake/cpm/patches/libcudacxx/install_rules.diff
  rapids-cmake/cpm/patches/libcudacxx/memory_resource.diff
  rapids-cmake/cpm/patches/libcudacxx/proclaim_return_type_nv_exec_check_disable.diff
  rapids-cmake/cpm/patches/libcudacxx/reroot_support.diff
  rapids-cmake/cpm/thrust.cmake
  rapids-cmake/cpm/versions.json
  rapids-cmake/cuda/patch_toolkit.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_cuco-libcudacxx-no-install-export.cmake
  testing/cpm/cpm_find-version-explicit-install.cmake
  testing/cpm/cpm_libcudacxx-after_cpmfind.cmake
  testing/cpm/cpm_libcudacxx-export.cmake
  testing/cpm/cpm_libcudacxx-simple.cmake
  testing/cpm/cpm_libcudacxx-verify-install-custom-libdir/CMakeLists.txt
  testing/cpm/cpm_thrust-export.cmake
  testing/cpm/cpm_thrust-simple.cmake
  testing/cpm/cpm_thrust-verify-post-find-code/CMakeLists.txt
  testing/cuda/CMakeLists.txt
  testing/cuda/patch_toolkit-nested/CMakeLists.txt
  testing/cuda/patch_toolkit-nested/subdir/CMakeLists.txt
  testing/cuda/patch_toolkit.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: breaking, improvement

#666 Remove deprecated rapids_export_find_package_* signatures
  rapids-cmake/export/find_package_file.cmake
  rapids-cmake/export/find_package_root.cmake
  testing/export/CMakeLists.txt
  testing/export/find_package_file-deprecated.cmake
  testing/export/find_package_root-deprecated.cmake
Labels: feature request, non-breaking

#668 Improve update-version.sh
  ci/release/update-version.sh
Labels: improvement, non-breaking

#669 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#670 add ASSOCIATED_TARGETS to function signature in rapids_cython_create_modules() docs
  rapids-cmake/cython-core/create_modules.cmake
Labels: doc, non-breaking

#674 rapids-cmake generated C++ files have current copyright year
  rapids-cmake/cmake/detail/compute_git_info.cmake
  rapids-cmake/cmake/template/git_revision.hpp.in
  rapids-cmake/cmake/template/version.hpp.in
  rapids-cmake/cmake/write_version_file.cmake
  testing/cmake/write_git_revision-simple/CMakeLists.txt
  testing/cmake/write_version-relative/CMakeLists.txt
  testing/utils/check_copyright_header.cmake
Labels: bug, non-breaking

#676 rapids_cpm_nvcomp has consistent behavior on every cmake execution
  rapids-cmake/cpm/nvcomp.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#678 Update to CPM 0.40.2 to fix CMake 3.30 deprecation warnings
  rapids-cmake/cpm/detail/download.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#679 Revert "Update to CPM 0.40.2 to fix CMake 3.30 deprecation warnings (#678)"
  rapids-cmake/cpm/detail/download.cmake
Labels: bug, non-breaking

#682 rapids-cmake tests no longer download CPM when `NO_CPM_CACHE` is set.
  rapids-cmake/cpm/detail/download.cmake
  testing/cpm/cpm_generate_pins-format-patches/CMakeLists.txt
  testing/cpm/cpm_generate_pins-override/CMakeLists.txt
  testing/utils/cmake_test.cmake
  testing/utils/fill_cache/CMakeLists.txt
  testing/utils/setup_cpm_cache.cmake
Labels: feature request, non-breaking

#684 Drop Python 3.9 support
  dependencies.yaml
Labels: improvement, non-breaking

#685 Add workaround for gcc bug in cuco
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#686 Update rapidsai/pre-commit-hooks
  .pre-commit-config.yaml
Labels: improvement, non-breaking
