Repository rapidsai/rapids-cmake, pull requests merged in 2024-12, with the labels that each got.

#710 Update to CCCL 2.7.0-rc2.
  rapids-cmake/cpm/versions.json
Labels: breaking, feature request

#724 Fix failures in cpm_generate_pins-nested tests
  rapids-cmake/cpm/detail/package_details.cmake
  testing/cpm/cpm_find-gtest-no-gmock/CMakeLists.txt
  testing/cpm/verify_generated_pins.cmake
  testing/utils/cmake_test.cmake
  testing/utils/fill_cache/CMakeLists.txt
  testing/utils/setup_cpm_cache.cmake
Labels: bug, non-breaking

#729 Update version references in workflow
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#733 Correct nvbench + conda test to explicitly pull spdlog
  testing/cpm/cpm_nvbench-conda-fmt.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#723 Bump cuco version to fetch various fixes and new features
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review

#732 fix signature in rapids_export() docs
  rapids-cmake/export/export.cmake
Labels: doc, non-breaking

#734 Require Cython to be found
  dependencies.yaml
  rapids-cmake/cython-core/init.cmake
Labels: improvement, non-breaking

#735 Bump cuco by one commit to include `cuco::arrow_filter_policy` updates
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review

#736 remove setup.cfg, use pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
  rapids-cmake/test/gpu_requirements.cmake
  setup.cfg
Labels: improvement, non-breaking
