Repository rapidsai/rapids-cmake, pull requests merged in 2024-04, with the labels that each got.

#576 rapids_cpm_gtest adds support for BUILD_STATIC
  cmake-format-rapids-cmake.json
  rapids-cmake/cpm/gtest.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_gtest-explicit-static.cmake
Labels: feature request, non-breaking, 3 - Ready for Review

#578 Better explain OVERRIDE option
  rapids-cmake/cpm/init.cmake
Labels: doc, non-breaking, 3 - Ready for Review

#585 rapids_cpm_gtest(BUILD_STATIC) now doesn't search for a local version
  rapids-cmake/cpm/gtest.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#571 Prevent path conflict in builds
  ci/build_cpp.sh
Labels: improvement, non-breaking

#586 Update rapids_test_install_relocatable to be aware of CMake 3.29
  rapids-cmake/test/detail/generate_installed_CTestTestfile.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#588 Ensure support_conda_env uses `isystem`
  rapids-cmake/cmake/support_conda_env.cmake
  testing/cmake/conda_env-build-envvar.cmake
  testing/cmake/conda_env-build.cmake
  testing/cmake/conda_env-cross-build-arm-envvar.cmake
  testing/cmake/conda_env-cross-build-arm.cmake
  testing/cmake/conda_env-cross-build-x86-envvar.cmake
  testing/cmake/conda_env-cross-build-x86.cmake
  testing/cmake/conda_env-prefix-envvar.cmake
  testing/cmake/conda_env-prefix.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#590 clarify language around how FetchContent is used in RAPIDS.cmake
  docs/basics.rst
Labels: doc, non-breaking

#589 fix docs for rapids_export_ functions
  docs/api.rst
Labels: doc, non-breaking

#591 use inline code formatting in docs for variables, functions, and modules
  docs/api.rst
  docs/basics.rst
  docs/dependency_tracking.rst
  docs/hardware_resources_and_testing.rst
  docs/packages/rapids_cpm_versions.rst
Labels: doc, non-breaking

#584 Bump NVBench version for new `main` hooks.
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#569 Bump cuco version to fetch the lastest set retrieve API
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking
