Repository rapidsai/rapids-cmake, pull requests merged in 2025-08, with the labels that each got.

#885 Properly store `source_subdir` values from `rapids_cpm_find` calls
  rapids-cmake/cpm/detail/pinning_write_file.cmake
  rapids-cmake/cpm/find.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_generate_pins-custom-src-dir/CMakeLists.txt
  testing/cpm/cpm_package_override-source-subdir.cmake
  testing/cpm/verify_generated_pins.cmake
  testing/cpm/verify_generated_pins/CMakeLists.txt
Labels: feature request, non-breaking

#887 Bump cuco version to fetch a bug fix for device retrieve APIs
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review

#893 rapids_export handles PROJECT_VERSION CMake 4.1+ change in behavior
  rapids-cmake/export/export.cmake
Labels: bug, non-breaking

#897 Use family arch flags whenever possible
  rapids-cmake/cuda/detail/detect_architectures.cmake
  rapids-cmake/cuda/set_architectures.cmake
  testing/cuda/set_arch-rapids.cmake
Labels: feature request, non-breaking

#899 set_architectures + NATIVE works even without a GPU
  rapids-cmake/cuda/detail/detect_architectures.cmake
  rapids-cmake/cuda/set_architectures.cmake
  testing/cuda/CMakeLists.txt
  testing/cuda/init_arch-native-no-gpu.cmake
  testing/cuda/validate-cuda-native.cmake
  testing/cuda/validate-cuda-rapids.cmake
Labels: bug, non-breaking

#900 change Architectures to avoid compute_100/120 code gen bug
  rapids-cmake/cuda/set_architectures.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#901 Updated dependencies.yaml to support CUDA 13
  .github/workflows/pr.yaml
  dependencies.yaml
  rapids-cmake/cpm/nvcomp.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_nvcomp-always-download-proprietary_binary.cmake
  testing/cpm/cpm_nvcomp-export.cmake
  testing/cpm/cpm_nvcomp-invalid-arch.cmake
  testing/cpm/cpm_nvcomp-override-clears-proprietary_binary.cmake
  testing/cpm/cpm_nvcomp-proprietary-off.cmake
  testing/cpm/cpm_nvcomp-proprietary-on.cmake
  testing/cpm/cpm_nvcomp-simple.cmake
  testing/utils/setup_cpm_cache.cmake
Labels: feature request, non-breaking

#896 Upgrade to nvCOMP 5.0.0.6
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_nvcomp-proprietary_binary-lib-location-common.cmake
Labels: breaking, feature request

#903 Update rapids-dependency-file-generator
  .pre-commit-config.yaml
Labels: improvement, non-breaking
