Repository rapidsai/rapids-cmake, pull requests merged in 2025-02, with the labels that each got.

#762 Add `verify-codeowners` hook
  .github/CODEOWNERS
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#767 add telemetry
  .github/workflows/pr.yaml
Labels: improvement, non-breaking

#768 Use shared-workflows branch-25.04
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#770 Use rapids-generate-version for package versions
  ci/build_cpp.sh
  conda/recipes/rapids_core_dependencies/meta.yaml
Labels: improvement, non-breaking

#773 Sanitize patch input to protect against CMake Language limitations
  rapids-cmake/cpm/detail/convert_patch_json.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_convert_patch_json-special-chars.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#765 Switch to using rapids-logger as a library
  rapids-cmake/cpm/rapids_logger.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_logger-simple.cmake
  testing/cpm/cpm_rmm-simple.cmake
Labels: breaking, improvement

#775 Fix tests broken by rapids-logger changes
  testing/cpm/cpm_generate_pins-nested/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple-via-variable/CMakeLists.txt
  testing/cpm/cpm_generate_pins-var-and-arg/CMakeLists.txt
Labels: bug, non-breaking

#771 Update `cuCollection` to not rely on `thrust::identity`
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#780 Update to nvcomp 4.2 which offers full blackwell support
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking, 3 - Ready for Review

#776 Set `-Wno-deprecated-gpu-targets` when compiling for RAPIDS architectures
  rapids-cmake/cuda/set_architectures.cmake
  testing/cuda/validate-cuda-native.cmake
  testing/cuda/validate-cuda-rapids.cmake
Labels: improvement, non-breaking

#784 Use conda-build instead of conda-mambabuild
  ci/build_cpp.sh
Labels: improvement, non-breaking
