Repository rapidsai/rapids-cmake, pull requests merged in 2025-05, with the labels that each got.

#831 Update to CCCL 3.0
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#835 Unset CUDAARCHS in test
  testing/cuda/init_arch-all-via-undef/CMakeLists.txt
Labels: bug, non-breaking

#838 Upgrade cuco version to include murmurhash performance fix
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 3 - Ready for Review, Performance

#842 Build and test with CUDA 12.9.0
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#845 Update to CCCL 2.8.4.
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#843 Bump cuco version to fetch multiple CCCL upgrade fixes
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking, 2 - In Progress

#846 Update to clang 20
  .pre-commit-config.yaml
  rapids-cmake/test/detail/generate_resource_spec.cpp
Labels: improvement, non-breaking

#847 Finish CUDA 12.9 migration and use branch-25.06 workflows
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking

#848 Forward-merge branch-25.06 into branch-25.08
  .pre-commit-config.yaml
  dependencies.yaml
  rapids-cmake/cpm/versions.json
  rapids-cmake/test/detail/generate_resource_spec.cpp
Labels: improvement, non-breaking

#849 explicitly provide 'script' to CI workflows
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
Labels: improvement, non-breaking

#844 Update to NVTX 3.2.0.
  rapids-cmake/cpm/nvtx3.cmake
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#854 Update to CCCL 3.0
  rapids-cmake/cpm/versions.json
Labels: breaking, improvement
