Repository rapidsai/rapids-cmake, pull requests merged in 2025-01, with the labels that each got.

#737 Add rapids-logger
  cmake-format-rapids-cmake.json
  docs/packages/packages.rst
  docs/packages/rapids_cpm_rapids_logger.rst
  rapids-cmake/cpm/rapids_logger.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_logger-simple.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: feature request, non-breaking

#738 Update logger hash
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#739 Add new global targets for rmm
  rapids-cmake/cpm/rmm.cmake
  testing/cpm/cpm_rmm-simple.cmake
Labels: improvement, non-breaking

#742 rapids_cpm_cccl use proper CCCL version value to compute install rules
  rapids-cmake/cpm/cccl.cmake
  testing/cpm/CMakeLists.txt
Labels: bug, non-breaking

#743 Use CCCL v2.7.0 final tag.
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_cccl-version-2-7.cmake
Labels: improvement, non-breaking

#741 Use GCC 13 in CUDA 12 conda builds.
  conda/recipes/rapids_core_dependencies/conda_build_config.yaml
  conda/recipes/rapids_core_dependencies/meta.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#744 Fetch cuco filter alignment fix to unblock RAPIDS CI
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#746 Add support for new architectures in CUDA 12.8
  rapids-cmake/cuda/set_architectures.cmake
Labels: feature request, non-breaking

#745 Use sysroot 2.17 on CUDA < 11.8.
  dependencies.yaml
Labels: bug, non-breaking

#749 Allow sysroot 2.28 in CUDA 11 jobs.
  dependencies.yaml
Labels: improvement, non-breaking

#754 Build and test with CUDA 12.8.0
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#756 Backport cccl PR 3578 to v2.7 to unblock CUDA 12.8 builds
  .pre-commit-config.yaml
  pyproject.toml
  rapids-cmake/cpm/patches/cccl/backport-suppress-execution-checks.patch
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#758 Migrate to NVKS for amd64 CI runners
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  .github/workflows/test.yaml
  .github/workflows/trigger-breaking-change-alert.yaml
Labels: improvement, non-breaking
