Repository rapidsai/rapids-cmake, pull requests merged in 2025-06, with the labels that each got.

#856 Fetch the atomic fix in CCCL 3.0
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, 3 - Ready for Review

#858 rapids_cpm_cccl: Update to new location of cccl-config
  rapids-cmake/cpm/cccl.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#859 rapids_cpm_cccl: Remove support for CCCL < 2.8
  rapids-cmake/cpm/cccl.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_cccl-version-2-5.cmake
  testing/cpm/cpm_cccl-version-2-8.cmake
  testing/cpm/cpm_cccl-version-3-0.cmake
Labels: breaking, feature request, 3 - Ready for Review

#857 Remove CCCL patches that aren't used anymore
  rapids-cmake/cpm/patches/cccl/backport-suppress-execution-checks.patch
Labels: bug, non-breaking, 3 - Ready for Review

#855 Remove CUDA 11 support
  dependencies.yaml
  rapids-cmake/cuda/set_architectures.cmake
Labels: breaking, improvement

#865 Remove nvidia and dask channels
  .pre-commit-config.yaml
Labels: improvement, non-breaking

#867 Rename `*.hpp.in` to `*.h.in` to signify that they are C headers
  rapids-cmake/cmake/template/git_revision.h.in
  rapids-cmake/cmake/template/version.h.in
  rapids-cmake/cmake/write_git_revision_file.cmake
  rapids-cmake/cmake/write_version_file.cmake
Labels: improvement, non-breaking
