Repository rapidsai/rapids-cmake, pull requests merged in 2025-03, with the labels that each got.

#789 Rollback to CPM 0.40.0
  rapids-cmake/cpm/detail/download.cmake
Labels: bug, non-breaking, 5 - Ready to Merge

#787 Sanitize patch inputs so that quotes are properly escaped
  rapids-cmake/cpm/detail/convert_patch_json.cmake
  testing/cpm/cpm_convert_patch_json-special-chars.cmake
Labels: bug, non-breaking, 3 - Ready for Review

#778 rapids_cpm_package_override: Always load overrides
  rapids-cmake/cpm/detail/package_details.cmake
  rapids-cmake/cpm/package_override.cmake
  testing/cpm/cpm_package_override-obey-cpm-source-var.cmake
Labels: feature request, non-breaking

#783 Add support for components in Cython `rapids_cython_create_modules`
  rapids-cmake/cython-core/create_modules.cmake
  testing/cython-core/CMakeLists.txt
  testing/cython-core/cython-core_create_modules_component/CMakeLists.txt
  testing/cython-core/cython-core_create_modules_component/check_installed_components.cmake
  testing/cython-core/cython-core_create_modules_component/test1.pyx
  testing/cython-core/cython-core_create_modules_component/test2.pyx
Labels: feature request, non-breaking

#790 Remove now superfluous fmt patch
  rapids-cmake/cpm/patches/fmt/fix_11_0_2_unreachable_loop.diff
  rapids-cmake/cpm/versions.json
Labels: breaking, improvement

#792 Also download fmt when building nvbench statically
  rapids-cmake/cpm/nvbench.cmake
Labels: bug, non-breaking

#795 Update gtest version
  rapids-cmake/cpm/versions.json
Labels: breaking, improvement

#802 Set correct compiler feature for `generate_ctest_json`
  rapids-cmake/test/generate_resource_spec.cmake
  testing/test/install_relocatable-complex/tests/CMakeLists.txt
Labels: bug, non-breaking
