Repository rapidsai/rapids-cmake, pull requests merged in 2025-04, with the labels that each got.

#811 Disable git_shallow for nvtx3 and bs_thread_pool
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#812 Use hashes instead of tags
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_init-override-multiple.cmake
  testing/cpm/cpm_package_override-defaults-with-different-casing.cmake
  testing/cpm/cpm_package_override-multiple-cmake-var.cmake
  testing/cpm/cpm_package_override-multiple.cmake
  testing/cpm/cpm_package_override-simple.cmake
  testing/cpm/verify_generated_pins/CMakeLists.txt
Labels: improvement, non-breaking

#815 Fix issue with how project pins are determined
  rapids-cmake/cpm/detail/pinning_write_file.cmake
  testing/cpm/cpm_generate_pins-simple/CMakeLists.txt
  testing/cpm/verify_generated_pins/CMakeLists.txt
Labels: bug, non-breaking

#816 Remove CMP0135 policy checks.
  RAPIDS.cmake
  rapids-cmake/cpm/detail/download_proprietary_binary.cmake
Labels: improvement, non-breaking

#809 Allow retrying downloads on network failures
  cmake-format-rapids-cmake.json
  docs/api.rst
  docs/command/rapids_cmake_download_with_retry.rst
  rapids-cmake/cmake/download_with_retry.cmake
  rapids-cmake/cpm/detail/download.cmake
  rapids-cmake/export/write_dependencies.cmake
  rapids-cmake/rapids-cmake.cmake
  testing/cmake/CMakeLists.txt
  testing/cmake/download_with_retry-basic.cmake
  testing/cmake/download_with_retry-overwrite.cmake
  testing/cmake/test_files/test1.txt
  testing/cmake/test_files/test2.txt
Labels: improvement, non-breaking

#818 Add `include_guard(GLOBAL)` to download_with_retry.cmake
  rapids-cmake/cmake/download_with_retry.cmake
  rapids-cmake/export/write_dependencies.cmake
Labels: bug, non-breaking

#822 Make `RAPIDS.cmake` inlineable without requiring updates
  RAPIDS.cmake
  README.md
  ci/release/update-version.sh
  docs/basics.rst
  testing/other/rapids_cmake-fetch-via-git/CMakeLists.txt
  testing/other/rapids_cmake-fetch-via-zip/CMakeLists.txt
  testing/other/rapids_cmake-multiple-cpm/CMakeLists.txt
  testing/other/rapids_cmake-multiple-simple/CMakeLists.txt
Labels: breaking, improvement

#825 Make `RAPIDS.cmake` inlineable without requiring updates
  RAPIDS.cmake
  README.md
  ci/release/update-version.sh
  docs/basics.rst
  testing/other/rapids_cmake-fetch-via-git/CMakeLists.txt
  testing/other/rapids_cmake-fetch-via-zip/CMakeLists.txt
  testing/other/rapids_cmake-multiple-cpm/CMakeLists.txt
  testing/other/rapids_cmake-multiple-simple/CMakeLists.txt
Labels: breaking, improvement

#807 Define `-DCUB_DISABLE_NAMESPACE_MAGIC` and `-DCUB_IGNORE_NAMESPACE_MAGIC_ERROR` in `rapids_cpm_cccl`
  rapids-cmake/cpm/cccl.cmake
Labels: improvement, non-breaking, 3 - Ready for Review

#828 Update cuCollections to avoid CCCL deprecation warnings
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking

#793 Update to CCCL 2.8.3
  rapids-cmake/cpm/versions.json
Labels: improvement, non-breaking
