Repository rapidsai/rapids-cmake, pull requests merged in 2025-07, with the labels that each got.

#868 add docs on CI workflow inputs
  .github/workflows/build.yaml
  .github/workflows/test.yaml
Labels: doc, non-breaking

#871 fix(docker): use versioned `-latest` tag for all `rapidsai` images
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  ci/release/update-version.sh
Labels: improvement, non-breaking

#873 chore: update docker version tags
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
Labels: improvement, non-breaking

#876 CCCL: disable PDL
  rapids-cmake/cpm/cccl.cmake
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking

#879 Update CCCL version tag for PDL disable
  rapids-cmake/cpm/versions.json
Labels: feature request, non-breaking

#882 Expand versions.json to have src_dir representation
  docs/cpm.rst
  rapids-cmake/cmake/detail/policy.cmake
  rapids-cmake/cpm/bs_thread_pool.cmake
  rapids-cmake/cpm/cccl.cmake
  rapids-cmake/cpm/cuco.cmake
  rapids-cmake/cpm/detail/download.cmake
  rapids-cmake/cpm/detail/package_details.cmake
  rapids-cmake/cpm/detail/package_info.cmake
  rapids-cmake/cpm/find.cmake
  rapids-cmake/cpm/fmt.cmake
  rapids-cmake/cpm/gbench.cmake
  rapids-cmake/cpm/gtest.cmake
  rapids-cmake/cpm/nvbench.cmake
  rapids-cmake/cpm/nvcomp.cmake
  rapids-cmake/cpm/nvtx3.cmake
  rapids-cmake/cpm/package_override.cmake
  rapids-cmake/cpm/rapids_logger.cmake
  rapids-cmake/cpm/rmm.cmake
  rapids-cmake/cpm/spdlog.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/cpm_find-patch-command-embedded/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-required-fails/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-required/CMakeLists.txt
  testing/cpm/cpm_find-patch-command/CMakeLists.txt
  testing/cpm/cpm_find-version-explicit-install.cmake
  testing/cpm/cpm_generate_patch_command-override-case-insensitive.cmake
  testing/cpm/cpm_generate_pins-format-patches/verify/CMakeLists.txt
  testing/cpm/cpm_generate_pins-override/verify/CMakeLists.txt
  testing/cpm/cpm_init-custom-default-multiple.cmake
  testing/cpm/cpm_init-custom-default-simple.cmake
  testing/cpm/cpm_init-custom-default-via-cmake-var.cmake
  testing/cpm/cpm_init-override-multiple.cmake
  testing/cpm/cpm_init-override-simple.cmake
  testing/cpm/cpm_init-override-via-cmake-var.cmake
  testing/cpm/cpm_package_override-add-new-project.cmake
  testing/cpm/cpm_package_override-before-init.cmake
  testing/cpm/cpm_package_override-defaults-with-different-casing.cmake
  testing/cpm/cpm_package_override-empty-patches.cmake
  testing/cpm/cpm_package_override-env-var-support.cmake
  testing/cpm/cpm_package_override-multiple-cmake-var.cmake
  testing/cpm/cpm_package_override-multiple.cmake
  testing/cpm/cpm_package_override-no-version-value.cmake
  testing/cpm/cpm_package_override-obey-cpm-source-var.cmake
  testing/cpm/cpm_package_override-patches.cmake
  testing/cpm/cpm_package_override-simple.cmake
  testing/cpm/cpm_proprietary-url-ctk-version-find-ctk.cmake
  testing/cpm/cpm_proprietary-url-ctk-version.cmake
  testing/cpm/cpm_proprietary-url-no-ctk-parsing.cmake
  testing/cpm/verify_generated_pins/CMakeLists.txt
  testing/utils/cmake_test.cmake
Labels: bug, non-breaking
