Repository rapidsai/rapids-cmake, pull requests merged in 2025-10, with the labels that each got.

#918 Remove spdlog and fmt and move to rapids-logger 0.2.1
  cmake-format-rapids-cmake.json
  dependencies.yaml
  docs/cpm.rst
  docs/packages/example_git_tag_override.json
  docs/packages/packages.rst
  docs/packages/rapids_cpm_fmt.rst
  docs/packages/rapids_cpm_spdlog.rst
  rapids-cmake/cpm/fmt.cmake
  rapids-cmake/cpm/init.cmake
  rapids-cmake/cpm/spdlog.cmake
  rapids-cmake/cpm/versions.json
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-embedded/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-embedded/override.json
  testing/cpm/cpm_find-patch-command-required-fails/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-required-fails/override.json
  testing/cpm/cpm_find-patch-command-required/CMakeLists.txt
  testing/cpm/cpm_find-patch-command-required/override.json
  testing/cpm/cpm_find-patch-command/CMakeLists.txt
  testing/cpm/cpm_find-patch-command/override.json
  testing/cpm/cpm_fmt-export.cmake
  testing/cpm/cpm_fmt-simple.cmake
  testing/cpm/cpm_fmt-static-lib.cmake
  testing/cpm/cpm_generate_pins-nested/CMakeLists.txt
  testing/cpm/cpm_generate_pins-nested/a/CMakeLists.txt
  testing/cpm/cpm_generate_pins-nested/b/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple-via-variable/CMakeLists.txt
  testing/cpm/cpm_generate_pins-simple/CMakeLists.txt
  testing/cpm/cpm_generate_pins-var-and-arg/CMakeLists.txt
  testing/cpm/cpm_nvbench-conda-fmt.cmake
  testing/cpm/cpm_spdlog-export.cmake
  testing/cpm/cpm_spdlog-external-fmt.cmake
  testing/cpm/cpm_spdlog-simple.cmake
  testing/cpm/verify_generated_pins.cmake
  testing/utils/fill_cache/CMakeLists.txt
Labels: breaking, improvement

#919 Adding `ENABLE_UNSTABLE` option for `rapids_cpm_cccl`
  cmake-format-rapids-cmake.json
  rapids-cmake/cpm/cccl.cmake
  testing/cpm/CMakeLists.txt
  testing/cpm/cpm_cccl-enable-unstable.cmake
Labels: feature request, non-breaking

#922 Bump CCCL to v3.0.3
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking, ! - Hotfix

#923 Update rapids-logger to 0.2.3
  rapids-cmake/cpm/versions.json
Labels: bug, non-breaking
